-- ============================================================================
-- Seed entry point
-- ============================================================================
-- LIVE database: run seed-catalog.sql only (specialties, locations, settings).
-- DEMO database: run seed-catalog.sql then seed-demo.sql (fictional people).
--
-- psql:
--   \i supabase/seed-catalog.sql
--   \i supabase/seed-demo.sql
--
-- Supabase SQL Editor: paste each file separately, catalog first.
-- Do not run seed-demo.sql on production.
-- ============================================================================
