import { Card, CardContent } from "@/components/ui/card";

/**
 * Default (cross-region) About page.
 *
 * Served on .com, .eu, and any non-UK host. The UK variant (`about-uk.tsx`)
 * is served on .co.uk and reinforces the intermediary positioning that the
 * terms-uk / regulatory-uk pages set out. Do not edit this file to make
 * UK-specific changes — those belong in `about-uk.tsx`.
 */

const COMPANY = "MyDoctors360";

export function AboutDefault() {
  return (
    <div className="mx-auto max-w-4xl space-y-8 py-12">
      <div>
        <h1 className="text-3xl font-bold">About {COMPANY}</h1>
        <p className="mt-2 text-muted-foreground">
          Private healthcare, on your terms.
        </p>
      </div>

      <Card>
        <CardContent className="prose prose-sm max-w-none p-6 dark:prose-invert sm:p-8">
          <h2>What we do</h2>
          <p>
            {COMPANY} connects patients with independent private doctors. You can search by
            specialty, location, language, or symptom; read verified profiles; check real
            reviews; compare prices in your own currency; and book an appointment — all in a
            few clicks.
          </p>

          <h2>How we&rsquo;re different</h2>
          <ul>
            <li>
              <strong>Transparent pricing.</strong> Every doctor sets their own fees, and you
              see them upfront. No hidden charges.
            </li>
            <li>
              <strong>Verified doctors.</strong> Every doctor is checked against the relevant
              medical register before they appear on the platform.
            </li>
            <li>
              <strong>Cross-border by default.</strong> Multi-language, multi-currency, and
              designed for patients who want choice.
            </li>
            <li>
              <strong>Your data, your control.</strong> We share medical information with a
              doctor only when you choose to share it.
            </li>
          </ul>

          <h2>What we don&rsquo;t do</h2>
          <p>
            We are a <strong>technology platform</strong>. We are not a healthcare provider and
            we do not provide medical advice, diagnosis, or treatment. The contract for any
            medical service is between you and the doctor you book with. In an emergency, please
            contact your local emergency services directly — this platform is not designed for
            urgent care.
          </p>

          <h2>Contact</h2>
          <p>
            General queries: <strong>hello@mydoctors360.com</strong>
            <br />
            Support: <strong>support@mydoctors360.com</strong>
            <br />
            Privacy: <strong>privacy@mydoctors360.com</strong>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
