export interface MedicalTestEntry {
  /** Unique identifier */
  id: string;
  /** i18n key for display label (e.g. "test.mri") */
  labelKey: string;
  /** Test category for grouping */
  category:
    | "blood"
    | "urine"
    | "imaging"
    | "cardiac"
    | "endoscopy"
    | "biopsy"
    | "allergy"
    | "other";
  /** Multiple phrasings patients might type */
  keywords: string[];
  /** Primary specialty slug to navigate to */
  primarySpecialty: string;
  /** Additional specialty slugs */
  relatedSpecialties: string[];
}

export const MEDICAL_TESTS: readonly MedicalTestEntry[] = [
  // ── Blood Tests ──────────────────────────────────────────────────
  {
    id: "cbc",
    labelKey: "test.cbc",
    category: "blood",
    keywords: ["cbc", "complete blood count", "full blood count", "blood count", "fbc", "blood test", "blood work"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["oncology"],
  },
  {
    id: "blood_glucose",
    labelKey: "test.blood_glucose",
    category: "blood",
    keywords: ["blood glucose", "blood sugar", "glucose test", "fasting glucose", "hba1c", "diabetes test", "sugar level"],
    primarySpecialty: "endocrinology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "lipid_panel",
    labelKey: "test.lipid_panel",
    category: "blood",
    keywords: ["lipid panel", "cholesterol test", "cholesterol", "triglycerides", "hdl", "ldl", "lipid profile"],
    primarySpecialty: "cardiology",
    relatedSpecialties: ["general-practice", "endocrinology"],
  },
  {
    id: "liver_function",
    labelKey: "test.liver_function",
    category: "blood",
    keywords: ["liver function", "liver test", "lft", "alt", "ast", "bilirubin", "liver panel", "liver enzymes"],
    primarySpecialty: "gastroenterology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "kidney_function",
    labelKey: "test.kidney_function",
    category: "blood",
    keywords: ["kidney function", "renal function", "creatinine", "bun", "egfr", "kidney test", "renal panel"],
    primarySpecialty: "nephrology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "thyroid_function",
    labelKey: "test.thyroid_function",
    category: "blood",
    keywords: ["thyroid function", "thyroid test", "tsh", "t3", "t4", "thyroid panel", "thyroid levels"],
    primarySpecialty: "endocrinology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "iron_studies",
    labelKey: "test.iron_studies",
    category: "blood",
    keywords: ["iron studies", "iron test", "ferritin", "iron levels", "iron deficiency", "transferrin"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["gastroenterology"],
  },
  {
    id: "vitamin_d",
    labelKey: "test.vitamin_d",
    category: "blood",
    keywords: ["vitamin d", "vitamin d test", "vitamin d levels", "25-hydroxyvitamin d"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["endocrinology", "rheumatology"],
  },
  {
    id: "vitamin_b12",
    labelKey: "test.vitamin_b12",
    category: "blood",
    keywords: ["vitamin b12", "b12 test", "b12 levels", "cobalamin", "folate"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["neurology"],
  },
  {
    id: "crp",
    labelKey: "test.crp",
    category: "blood",
    keywords: ["crp", "c-reactive protein", "inflammation test", "esr", "sed rate", "inflammatory markers"],
    primarySpecialty: "rheumatology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "coagulation",
    labelKey: "test.coagulation",
    category: "blood",
    keywords: ["coagulation", "blood clotting", "inr", "pt", "ptt", "clotting test", "d-dimer"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["cardiology"],
  },
  {
    id: "hormone_panel",
    labelKey: "test.hormone_panel",
    category: "blood",
    keywords: ["hormone panel", "hormone test", "hormone levels", "testosterone", "estrogen", "progesterone", "cortisol", "hormones"],
    primarySpecialty: "endocrinology",
    relatedSpecialties: ["gynecology", "urology"],
  },
  {
    id: "psa",
    labelKey: "test.psa",
    category: "blood",
    keywords: ["psa", "prostate specific antigen", "prostate test", "prostate cancer screening"],
    primarySpecialty: "urology",
    relatedSpecialties: ["oncology"],
  },
  {
    id: "sti_panel",
    labelKey: "test.sti_panel",
    category: "blood",
    keywords: ["sti test", "std test", "sti panel", "sexually transmitted", "hiv test", "syphilis test", "hepatitis test", "std screening"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["urology", "gynecology"],
  },
  {
    id: "tumor_markers",
    labelKey: "test.tumor_markers",
    category: "blood",
    keywords: ["tumor markers", "cancer markers", "ca-125", "cea", "afp", "cancer blood test"],
    primarySpecialty: "oncology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "autoimmune_panel",
    labelKey: "test.autoimmune_panel",
    category: "blood",
    keywords: ["autoimmune panel", "ana", "autoimmune test", "rheumatoid factor", "anti-ccp", "autoantibodies"],
    primarySpecialty: "rheumatology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "blood_type",
    labelKey: "test.blood_type",
    category: "blood",
    keywords: ["blood type", "blood group", "blood typing", "rh factor", "cross match"],
    primarySpecialty: "general-practice",
    relatedSpecialties: [],
  },
  {
    id: "electrolytes",
    labelKey: "test.electrolytes",
    category: "blood",
    keywords: ["electrolytes", "sodium", "potassium", "calcium", "magnesium", "electrolyte panel"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["nephrology"],
  },
  {
    id: "allergy_blood_test",
    labelKey: "test.allergy_blood_test",
    category: "blood",
    keywords: ["allergy blood test", "ige test", "rast test", "specific ige", "allergy panel"],
    primarySpecialty: "allergy",
    relatedSpecialties: ["general-practice"],
  },

  // ── Urine Tests ──────────────────────────────────────────────────
  {
    id: "urinalysis",
    labelKey: "test.urinalysis",
    category: "urine",
    keywords: ["urinalysis", "urine test", "urine analysis", "urine dipstick", "urine sample"],
    primarySpecialty: "general-practice",
    relatedSpecialties: ["nephrology", "urology"],
  },
  {
    id: "urine_culture",
    labelKey: "test.urine_culture",
    category: "urine",
    keywords: ["urine culture", "urine infection test", "uti test", "urine bacteria", "urine sensitivity"],
    primarySpecialty: "urology",
    relatedSpecialties: ["general-practice", "nephrology"],
  },
  {
    id: "24hr_urine",
    labelKey: "test.24hr_urine",
    category: "urine",
    keywords: ["24 hour urine", "24hr urine collection", "urine collection", "24 hour urine test"],
    primarySpecialty: "nephrology",
    relatedSpecialties: ["endocrinology"],
  },
  {
    id: "urine_drug_screen",
    labelKey: "test.urine_drug_screen",
    category: "urine",
    keywords: ["drug screen", "drug test", "urine drug test", "toxicology screen"],
    primarySpecialty: "general-practice",
    relatedSpecialties: [],
  },
  {
    id: "pregnancy_test",
    labelKey: "test.pregnancy_test",
    category: "urine",
    keywords: ["pregnancy test", "hcg test", "pregnancy", "am i pregnant"],
    primarySpecialty: "gynecology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "microalbumin",
    labelKey: "test.microalbumin",
    category: "urine",
    keywords: ["microalbumin", "urine albumin", "albumin creatinine ratio", "acr", "kidney screening"],
    primarySpecialty: "nephrology",
    relatedSpecialties: ["endocrinology"],
  },

  // ── Imaging ──────────────────────────────────────────────────────
  {
    id: "xray",
    labelKey: "test.xray",
    category: "imaging",
    keywords: ["x-ray", "xray", "x ray", "radiograph", "plain film"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["orthopedics", "pulmonology"],
  },
  {
    id: "ultrasound",
    labelKey: "test.ultrasound",
    category: "imaging",
    keywords: ["ultrasound", "sonography", "ultrasound scan", "sonogram", "echo"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["gynecology", "gastroenterology"],
  },
  {
    id: "mri",
    labelKey: "test.mri",
    category: "imaging",
    keywords: ["mri", "magnetic resonance imaging", "mri scan", "magnetic resonance"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["neurology", "orthopedics"],
  },
  {
    id: "ct_scan",
    labelKey: "test.ct_scan",
    category: "imaging",
    keywords: ["ct scan", "cat scan", "computed tomography", "ct", "ct imaging"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["pulmonology", "oncology"],
  },
  {
    id: "mammography",
    labelKey: "test.mammography",
    category: "imaging",
    keywords: ["mammography", "mammogram", "breast scan", "breast screening", "breast x-ray"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["gynecology", "oncology"],
  },
  {
    id: "dexa_scan",
    labelKey: "test.dexa_scan",
    category: "imaging",
    keywords: ["dexa scan", "bone density scan", "dxa", "bone density test", "osteoporosis scan"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["rheumatology", "endocrinology"],
  },
  {
    id: "doppler",
    labelKey: "test.doppler",
    category: "imaging",
    keywords: ["doppler", "doppler ultrasound", "vascular ultrasound", "blood flow scan", "doppler scan"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["cardiology"],
  },
  {
    id: "pet_scan",
    labelKey: "test.pet_scan",
    category: "imaging",
    keywords: ["pet scan", "pet ct", "positron emission tomography", "pet imaging"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["oncology"],
  },
  {
    id: "bone_scan",
    labelKey: "test.bone_scan",
    category: "imaging",
    keywords: ["bone scan", "bone scintigraphy", "nuclear bone scan"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["orthopedics", "oncology"],
  },
  {
    id: "abdominal_ultrasound",
    labelKey: "test.abdominal_ultrasound",
    category: "imaging",
    keywords: ["abdominal ultrasound", "abdomen scan", "abdominal scan", "liver ultrasound", "gallbladder ultrasound"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["gastroenterology"],
  },
  {
    id: "pelvic_ultrasound",
    labelKey: "test.pelvic_ultrasound",
    category: "imaging",
    keywords: ["pelvic ultrasound", "pelvic scan", "transvaginal ultrasound", "ovarian scan"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["gynecology", "urology"],
  },
  {
    id: "thyroid_ultrasound",
    labelKey: "test.thyroid_ultrasound",
    category: "imaging",
    keywords: ["thyroid ultrasound", "thyroid scan", "neck ultrasound", "thyroid imaging"],
    primarySpecialty: "radiology",
    relatedSpecialties: ["endocrinology"],
  },

  // ── Cardiac Tests ────────────────────────────────────────────────
  {
    id: "ecg",
    labelKey: "test.ecg",
    category: "cardiac",
    keywords: ["ecg", "ekg", "electrocardiogram", "heart trace", "heart rhythm test"],
    primarySpecialty: "cardiology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "echocardiogram",
    labelKey: "test.echocardiogram",
    category: "cardiac",
    keywords: ["echocardiogram", "echo", "heart ultrasound", "cardiac ultrasound", "heart echo"],
    primarySpecialty: "cardiology",
    relatedSpecialties: [],
  },
  {
    id: "holter_monitor",
    labelKey: "test.holter_monitor",
    category: "cardiac",
    keywords: ["holter monitor", "holter", "24 hour ecg", "heart monitor", "ambulatory ecg", "cardiac monitor"],
    primarySpecialty: "cardiology",
    relatedSpecialties: [],
  },
  {
    id: "stress_test",
    labelKey: "test.stress_test",
    category: "cardiac",
    keywords: ["stress test", "exercise test", "treadmill test", "cardiac stress test", "exercise ecg"],
    primarySpecialty: "cardiology",
    relatedSpecialties: [],
  },
  {
    id: "cardiac_catheterization",
    labelKey: "test.cardiac_catheterization",
    category: "cardiac",
    keywords: ["cardiac catheterization", "heart catheterization", "coronary angiogram", "angiography", "cardiac cath"],
    primarySpecialty: "cardiology",
    relatedSpecialties: [],
  },
  {
    id: "ambulatory_bp",
    labelKey: "test.ambulatory_bp",
    category: "cardiac",
    keywords: ["ambulatory blood pressure", "24 hour blood pressure", "abpm", "blood pressure monitoring"],
    primarySpecialty: "cardiology",
    relatedSpecialties: ["general-practice"],
  },

  // ── Endoscopy ────────────────────────────────────────────────────
  {
    id: "gastroscopy",
    labelKey: "test.gastroscopy",
    category: "endoscopy",
    keywords: ["gastroscopy", "upper endoscopy", "egd", "stomach scope", "oesophagogastroduodenoscopy"],
    primarySpecialty: "gastroenterology",
    relatedSpecialties: [],
  },
  {
    id: "colonoscopy",
    labelKey: "test.colonoscopy",
    category: "endoscopy",
    keywords: ["colonoscopy", "colon scope", "bowel scope", "colon screening", "colon exam"],
    primarySpecialty: "gastroenterology",
    relatedSpecialties: ["oncology"],
  },
  {
    id: "bronchoscopy",
    labelKey: "test.bronchoscopy",
    category: "endoscopy",
    keywords: ["bronchoscopy", "lung scope", "airway scope", "bronchial exam"],
    primarySpecialty: "pulmonology",
    relatedSpecialties: [],
  },
  {
    id: "cystoscopy",
    labelKey: "test.cystoscopy",
    category: "endoscopy",
    keywords: ["cystoscopy", "bladder scope", "bladder exam", "urethroscopy"],
    primarySpecialty: "urology",
    relatedSpecialties: [],
  },
  {
    id: "colposcopy",
    labelKey: "test.colposcopy",
    category: "endoscopy",
    keywords: ["colposcopy", "cervical exam", "cervical scope", "cervix examination"],
    primarySpecialty: "gynecology",
    relatedSpecialties: [],
  },
  {
    id: "sigmoidoscopy",
    labelKey: "test.sigmoidoscopy",
    category: "endoscopy",
    keywords: ["sigmoidoscopy", "flexi sig", "flexible sigmoidoscopy", "lower bowel scope"],
    primarySpecialty: "gastroenterology",
    relatedSpecialties: [],
  },

  // ── Biopsy ───────────────────────────────────────────────────────
  {
    id: "skin_biopsy",
    labelKey: "test.skin_biopsy",
    category: "biopsy",
    keywords: ["skin biopsy", "mole biopsy", "skin sample", "punch biopsy"],
    primarySpecialty: "dermatology",
    relatedSpecialties: ["oncology"],
  },
  {
    id: "tissue_biopsy",
    labelKey: "test.tissue_biopsy",
    category: "biopsy",
    keywords: ["tissue biopsy", "biopsy", "tissue sample", "surgical biopsy"],
    primarySpecialty: "oncology",
    relatedSpecialties: ["general-practice"],
  },
  {
    id: "pap_smear",
    labelKey: "test.pap_smear",
    category: "biopsy",
    keywords: ["pap smear", "pap test", "cervical smear", "cervical screening", "smear test"],
    primarySpecialty: "gynecology",
    relatedSpecialties: [],
  },
  {
    id: "fine_needle_aspiration",
    labelKey: "test.fine_needle_aspiration",
    category: "biopsy",
    keywords: ["fine needle aspiration", "fna", "needle biopsy", "aspiration biopsy"],
    primarySpecialty: "oncology",
    relatedSpecialties: ["endocrinology"],
  },

  // ── Allergy Tests ────────────────────────────────────────────────
  {
    id: "skin_prick_test",
    labelKey: "test.skin_prick_test",
    category: "allergy",
    keywords: ["skin prick test", "allergy skin test", "prick test", "skin allergy test"],
    primarySpecialty: "allergy",
    relatedSpecialties: ["dermatology"],
  },
  {
    id: "patch_test",
    labelKey: "test.patch_test",
    category: "allergy",
    keywords: ["patch test", "contact allergy test", "dermatitis test", "skin patch test"],
    primarySpecialty: "allergy",
    relatedSpecialties: ["dermatology"],
  },
  {
    id: "food_allergy_test",
    labelKey: "test.food_allergy_test",
    category: "allergy",
    keywords: ["food allergy test", "food intolerance test", "food sensitivity", "elimination diet test"],
    primarySpecialty: "allergy",
    relatedSpecialties: ["gastroenterology", "nutrition"],
  },

  // ── Other / Specialist Tests ─────────────────────────────────────
  {
    id: "spirometry",
    labelKey: "test.spirometry",
    category: "other",
    keywords: ["spirometry", "lung function test", "breathing test", "pulmonary function", "pft"],
    primarySpecialty: "pulmonology",
    relatedSpecialties: ["allergy"],
  },
  {
    id: "sleep_study",
    labelKey: "test.sleep_study",
    category: "other",
    keywords: ["sleep study", "polysomnography", "sleep test", "sleep apnea test", "sleep lab"],
    primarySpecialty: "pulmonology",
    relatedSpecialties: ["neurology", "ent"],
  },
  {
    id: "eeg",
    labelKey: "test.eeg",
    category: "other",
    keywords: ["eeg", "electroencephalogram", "brain wave test", "brain activity test"],
    primarySpecialty: "neurology",
    relatedSpecialties: [],
  },
  {
    id: "emg",
    labelKey: "test.emg",
    category: "other",
    keywords: ["emg", "electromyography", "nerve conduction study", "ncs", "muscle test", "nerve test"],
    primarySpecialty: "neurology",
    relatedSpecialties: ["orthopedics"],
  },
  {
    id: "audiometry",
    labelKey: "test.audiometry",
    category: "other",
    keywords: ["audiometry", "hearing test", "hearing assessment", "audiogram"],
    primarySpecialty: "ent",
    relatedSpecialties: [],
  },
  {
    id: "visual_field_test",
    labelKey: "test.visual_field_test",
    category: "other",
    keywords: ["visual field test", "eye field test", "perimetry", "peripheral vision test"],
    primarySpecialty: "ophthalmology",
    relatedSpecialties: ["neurology"],
  },
  {
    id: "eye_exam",
    labelKey: "test.eye_exam",
    category: "other",
    keywords: ["eye exam", "eye test", "vision test", "sight test", "eye check"],
    primarySpecialty: "ophthalmology",
    relatedSpecialties: [],
  },
  {
    id: "dental_xray",
    labelKey: "test.dental_xray",
    category: "imaging",
    keywords: ["dental x-ray", "dental xray", "dental radiograph", "panoramic x-ray", "opg"],
    primarySpecialty: "dentistry",
    relatedSpecialties: [],
  },
  {
    id: "skin_allergy_test",
    labelKey: "test.skin_allergy_test",
    category: "allergy",
    keywords: ["skin allergy", "contact dermatitis test", "allergy testing", "allergy test"],
    primarySpecialty: "allergy",
    relatedSpecialties: ["dermatology"],
  },
  {
    id: "body_composition",
    labelKey: "test.body_composition",
    category: "other",
    keywords: ["body composition", "body fat test", "bmi test", "body analysis", "metabolic test"],
    primarySpecialty: "nutrition",
    relatedSpecialties: ["endocrinology"],
  },
  {
    id: "urodynamics",
    labelKey: "test.urodynamics",
    category: "other",
    keywords: ["urodynamics", "bladder function test", "urodynamic study", "bladder pressure test"],
    primarySpecialty: "urology",
    relatedSpecialties: ["gynecology"],
  },
  {
    id: "bone_marrow_biopsy",
    labelKey: "test.bone_marrow_biopsy",
    category: "biopsy",
    keywords: ["bone marrow biopsy", "bone marrow aspiration", "bone marrow test"],
    primarySpecialty: "oncology",
    relatedSpecialties: [],
  },
] as const;
