export const SPECIALTIES = [
  { nameKey: "specialty.general_practice", slug: "general-practice", icon: "Stethoscope" },
  { nameKey: "specialty.cardiology", slug: "cardiology", icon: "Heart" },
  { nameKey: "specialty.dermatology", slug: "dermatology", icon: "Sparkles" },
  { nameKey: "specialty.orthopedics", slug: "orthopedics", icon: "Bone" },
  { nameKey: "specialty.neurology", slug: "neurology", icon: "Brain" },
  { nameKey: "specialty.psychiatry", slug: "psychiatry", icon: "Brain" },
  { nameKey: "specialty.psychology", slug: "psychology", icon: "HeartHandshake" },
  { nameKey: "specialty.ophthalmology", slug: "ophthalmology", icon: "Eye" },
  { nameKey: "specialty.ent", slug: "ent", icon: "Ear" },
  { nameKey: "specialty.gynecology", slug: "gynecology", icon: "Baby" },
  { nameKey: "specialty.urology", slug: "urology", icon: "Activity" },
  { nameKey: "specialty.gastroenterology", slug: "gastroenterology", icon: "Apple" },
  { nameKey: "specialty.endocrinology", slug: "endocrinology", icon: "Droplets" },
  { nameKey: "specialty.pulmonology", slug: "pulmonology", icon: "Wind" },
  { nameKey: "specialty.oncology", slug: "oncology", icon: "Shield" },
  { nameKey: "specialty.pediatrics", slug: "pediatrics", icon: "Baby" },
  { nameKey: "specialty.dentistry", slug: "dentistry", icon: "Smile" },
  { nameKey: "specialty.aesthetic_medicine", slug: "aesthetic-medicine", icon: "Sparkles" },
  { nameKey: "specialty.physiotherapy", slug: "physiotherapy", icon: "Activity" },
  { nameKey: "specialty.radiology", slug: "radiology", icon: "Scan" },
  { nameKey: "specialty.nutrition", slug: "nutrition", icon: "Apple" },
  { nameKey: "specialty.allergy", slug: "allergy", icon: "Flower" },
  { nameKey: "specialty.rheumatology", slug: "rheumatology", icon: "Bone" },
  { nameKey: "specialty.nephrology", slug: "nephrology", icon: "Droplets" },
] as const;
