export const SUBSCRIPTION_PLANS = [
  {
    id: "free",
    name: "Free",
    description: "Get started with your online presence",
    priceMonthly: 0,
    currency: "EUR",
    features: [
      "Public doctor profile",
    ],
  },
  {
    id: "professional",
    name: "Professional",
    description: "Everything you need to grow your practice",
    priceMonthly: 9900,
    currency: "EUR",
    features: [
      "Doctor profile",
      "Online booking calendar",
      "Unlimited bookings",
      "Email reminders",
      "SMS & WhatsApp reminders",
      "Video consultations",
      "Basic & advanced analytics",
      "Patient CRM",
      "Priority support",
    ],
    popular: true,
  },
  {
    id: "premium",
    name: "Premium",
    description: "Maximum visibility and advanced features",
    priceMonthly: 19900,
    currency: "EUR",
    features: [
      "Everything in Professional",
      "Featured profile placement",
      "AI workflow automation",
      "Custom branding",
      "API access",
      "Dedicated account manager",
    ],
  },
  {
    id: "clinic",
    name: "Clinic",
    description: "For clinics and group practices with 5+ doctors",
    priceMonthly: 79900,
    currency: "EUR",
    features: [
      "Everything in Premium",
      "Up to 10 doctor profiles",
      "Centralized clinic dashboard",
      "Multi-doctor scheduling",
      "Shared patient records",
      "Clinic branding & landing page",
      "Team performance analytics",
      "Bulk booking management",
      "Priority onboarding & training",
      "Dedicated account manager",
    ],
  },
] as const;
