export const SUBSCRIPTION_PLANS = [
  {
    id: "free",
    name: "Free",
    description: "Get started with your online presence",
    priceMonthly: 0,
    currency: "EUR",
    features: [
      "Public doctor profile",
    ],
  },
  {
    id: "professional",
    name: "Professional",
    description: "Individual plans for Doctors",
    priceMonthly: 9900,
    currency: "EUR",
    features: [
      "1 User Doctor Profile",
      "Online booking calendar",
      "Unlimited bookings",
      "Email reminders",
      "SMS & WhatsApp reminders",
      "Video consultations",
      "Basic & advanced analytics",
      "Patient CRM",
      "Priority support",
    ],
  },
  {
    id: "premium",
    name: "Premium",
    description: "Individual plans for Doctors",
    priceMonthly: 19900,
    currency: "EUR",
    features: [
      "Everything in Professional",
      "Featured profile placement",
      "AI workflow automation",
      "Custom branding",
      "API access",
      "Dedicated account manager",
    ],
    popular: true,
  },
  {
    id: "clinic",
    name: "Clinic Starter Pack",
    description: "Everything you need to launch your clinic online",
    priceMonthly: 79900,
    currency: "EUR",
    features: [
      "Everything in Professional & Premium",
      "Up to 5 doctor profiles",
      "3 hours of dedicated onboarding",
      "Custom branding on your profile",
      "Centralized clinic dashboard",
      "Multi-doctor scheduling",
      "Team performance analytics",
      "Dedicated account manager",
    ],
  },
  {
    id: "testing_service",
    name: "Medical Testing",
    description: "For labs, clinics & nurses offering diagnostic services",
    priceMonthly: 4900,
    currency: "GBP",
    features: [
      "Online booking calendar",
      "Unlimited bookings",
      "Email reminders",
      "SMS & WhatsApp reminders",
    ],
  },
] as const;
