import { Card, CardContent } from "@/components/ui/card";
import { PRIVACY_PUBLISH_DATE } from "./privacy-publish-date";

/**
 * Default (cross-region) Privacy Policy.
 *
 * Served on .com, .eu, and any non-UK host. The UK variant
 * (`privacy-uk.tsx`) is served on .co.uk with ICO / DPO / controller-processor
 * detail and a full sub-processor list. Do not edit this file to make
 * UK-specific changes — those belong in `privacy-uk.tsx`. This content should
 * stay byte-for-byte equivalent to what we&rsquo;ve always served on .com/.eu
 * unless a global update is needed.
 */

const COMPANY = "MyDoctors360";

export function PrivacyDefault() {
  return (
    <div className="mx-auto max-w-4xl space-y-8 py-12">
      <div>
        <h1 className="text-3xl font-bold">Privacy Policy</h1>
        <p className="mt-2 text-muted-foreground">
          Effective Date: {PRIVACY_PUBLISH_DATE}
        </p>
        <p className="text-muted-foreground">
          Last updated: {PRIVACY_PUBLISH_DATE}
        </p>
      </div>

      <Card>
        <CardContent className="prose prose-sm max-w-none p-6 dark:prose-invert sm:p-8">
          <h2>1. Introduction</h2>
          <p>
            {COMPANY} (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;) operates a healthcare marketplace
            connecting patients with private medical practitioners. This Privacy Policy explains how we collect,
            use, store, and protect your personal data in compliance with the UK General Data Protection Regulation
            (UK GDPR) and the Data Protection Act 2018.
          </p>

          <h2>2. Data Controller</h2>
          <p>
            {COMPANY} is the data controller for personal data processed through our platform.
            For questions about this policy, contact us at <strong>privacy@mydoctors360.com</strong>.
          </p>

          <h2>3. Data We Collect</h2>
          <h3>3.1 Account Information</h3>
          <p>Name, email address, phone number, and password (hashed) when you create an account.</p>

          <h3>3.2 Medical Information</h3>
          <p>
            Health conditions, allergies, medications, blood type, and other medical information you
            voluntarily provide in your medical profile or during consultations. This constitutes
            &ldquo;special category data&rdquo; under UK GDPR.
          </p>

          <h3>3.3 Booking &amp; Payment Data</h3>
          <p>
            Appointment details, consultation notes, and payment information processed securely via Stripe.
            We do not store full credit card numbers on our servers.
          </p>

          <h3>3.4 Technical Data</h3>
          <p>
            IP address, browser type, device information, and usage analytics (subject to your cookie preferences).
          </p>

          <h2>4. Legal Basis for Processing</h2>
          <ul>
            <li><strong>Contract performance</strong> — To provide our booking and marketplace services.</li>
            <li><strong>Explicit consent</strong> — For processing medical/health data (Article 9(2)(a) UK GDPR).</li>
            <li><strong>Legitimate interests</strong> — For platform security, fraud prevention, and service improvement.</li>
            <li><strong>Legal obligation</strong> — To comply with healthcare regulations and tax requirements.</li>
          </ul>

          <h2>5. How We Use Your Data</h2>
          <ul>
            <li>Facilitate appointment bookings between patients and doctors.</li>
            <li>Process payments via Stripe Connect.</li>
            <li>Send appointment reminders and booking confirmations.</li>
            <li>Enable doctors to provide medical care with your health context (with your consent).</li>
            <li>Improve our platform and resolve support queries.</li>
          </ul>

          <h2>6. Data Sharing</h2>
          <p>We share your data only with:</p>
          <ul>
            <li><strong>Healthcare providers</strong> — Doctors you book with (medical profile shared only with your explicit consent).</li>
            <li><strong>Stripe</strong> — Payment processing (PCI DSS compliant).</li>
            <li><strong>Resend</strong> — Email delivery service.</li>
            <li><strong>Supabase</strong> — Database hosting (EU/UK data centres).</li>
            <li><strong>Sentry</strong> — Error monitoring (anonymised data only).</li>
          </ul>
          <p>We do not sell your data to third parties.</p>

          <h2>7. Data Retention</h2>
          <p>
            {`If you ask us to delete your account, we'll close it, remove your name, email, phone number and address, and delete anything we don't need to keep. Some records must be kept by law or for your care, even after your account is closed. These include consultation and prescription records (usually 8 years after your last consultation, longer for children), payment and booking records (6 years for tax and legal reasons), and doctor registration and insurance details (6 years after a doctor leaves). We keep these securely with access restricted, use them only for those reasons, and delete them when the period ends. You can still ask to see them.`}
          </p>
          <ul>
            <li><strong>Booking and consultation-booking records:</strong> 6 years after the end of the financial year in which the booking took place, for tax and legal reasons. Your name and contact details are removed if you close your account.</li>
            <li><strong>Payment, refund, wallet credit and statement records:</strong> 6 years after the end of the financial year in which the payment took place, as required for tax (HMRC) and legal claims.</li>
            <li><strong>Medical and consultation records (including prescriptions, consultation notes, and health information shared with a doctor for a booking):</strong> for adults, 8 years after your last consultation; for children, until their 25th birthday (26th if they were 17 at their last consultation), or 8 years, whichever is later. These records are kept even if you close your account or ask us to delete your data, because the law and your ongoing care require it. Access is restricted, and you can still ask to see them. Health information you entered but never shared with a doctor for a booking is deleted when you ask.</li>
            <li><strong>Prescription audit records:</strong> kept for the same period as the prescription they relate to, and cannot be altered.</li>
            <li><strong>Security and access logs:</strong> 2 years.</li>
            <li><strong>Pending bookings</strong> — Automatically deleted after 15 minutes (patient) or 48 hours (admin-created) if payment is not completed.</li>
          </ul>

          <h2>8. Your Rights</h2>
          <p>Under UK GDPR, you have the right to:</p>
          <ul>
            <li><strong>Access</strong> your personal data (available via Dashboard &gt; Settings &gt; Export Data).</li>
            <li><strong>Rectification</strong> — correct inaccurate data via your profile settings.</li>
            <li><strong>Erasure</strong> — delete your account (Dashboard &gt; Settings &gt; Delete Account).</li>
            <li><strong>Restrict processing</strong> — contact us to limit how we use your data.</li>
            <li><strong>Data portability</strong> — export your data in JSON format.</li>
            <li><strong>Object</strong> — to processing based on legitimate interests.</li>
            <li><strong>Withdraw consent</strong> — for medical data sharing at any time.</li>
          </ul>

          <h2>9. Data Subject Access Requests (DSAR)</h2>
          <h3>How to Submit a DSAR</h3>
          <p>
            To exercise any of the rights listed above, email us at{" "}
            <strong>privacy@mydoctors360.com</strong> with the subject line
            &ldquo;Data Subject Access Request&rdquo;.
          </p>

          <h3>What to Include</h3>
          <ul>
            <li>Your full name.</li>
            <li>The email address associated with your {COMPANY} account.</li>
            <li>
              A description of your request (e.g., access, deletion, rectification,
              data portability).
            </li>
          </ul>

          <h3>Identity Verification</h3>
          <p>
            To protect your personal data, we may ask you to provide proof of identity
            before processing your request. This is a security measure and does not
            affect your rights.
          </p>

          <h3>Response Time</h3>
          <p>
            We will respond to your verified request within <strong>30 calendar days</strong>,
            as required by UK GDPR Article 12. In complex cases or where we receive a
            high volume of requests, we may extend this period by a further 60 days. If
            an extension is necessary, we will inform you within the initial 30-day period
            and explain the reason for the delay.
          </p>

          <h3>Self-Service Options</h3>
          <p>
            You can also manage your data directly from your account. Go to{" "}
            <strong>Dashboard &gt; Settings &gt; Data &amp; Privacy</strong> to export
            your data or delete your account without submitting a formal request.
          </p>

          <h3>Cost</h3>
          <p>
            DSAR requests are provided free of charge. We reserve the right to charge a
            reasonable fee for requests that are manifestly unfounded or excessive, or to
            refuse to act on such requests, in accordance with UK GDPR Article 12(5).
          </p>

          <h3>Complaints</h3>
          <p>
            If you are unsatisfied with our response to your DSAR, you have the right to
            lodge a complaint with the Information Commissioner&apos;s Office (ICO) at{" "}
            <strong>ico.org.uk</strong>.
          </p>

          <h2>10. Cookies</h2>
          <p>
            We use essential cookies for authentication and optional analytics cookies (subject to your consent).
            See our cookie consent banner for granular control.
          </p>

          <h2>11. Security</h2>
          <p>
            We protect your data with HTTPS/TLS encryption in transit, row-level security policies in our
            database, multi-factor authentication options, and regular security audits.
          </p>

          <h2>12. International Transfers</h2>
          <p>
            Your data is primarily stored in the EU/UK. Where transfers outside the UK are necessary
            (e.g., for email delivery), we ensure adequate safeguards are in place under UK GDPR.
          </p>

          <h2>13. Children</h2>
          <p>
            Our services are not directed to individuals under 16. We do not knowingly collect data from children.
          </p>

          <h2>14. Changes to This Policy</h2>
          <p>
            We may update this policy periodically. Significant changes will be notified via email or in-app notification.
            Continued use after changes constitutes acceptance.
          </p>

          <h2>15. Contact &amp; Complaints</h2>
          <p>
            For privacy queries: <strong>privacy@mydoctors360.com</strong>
          </p>
          <p>
            You have the right to lodge a complaint with the Information Commissioner&apos;s Office (ICO)
            at <strong>ico.org.uk</strong>.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
