-- Migration: 00083_medications_autocomplete
-- Description: Create medications table with trigram fuzzy search for autocomplete
-- Date: 2026-04-04

-- 1. Enable pg_trgm extension for fuzzy text search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Create medications table
CREATE TABLE IF NOT EXISTS medications (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  generic_name TEXT,
  category TEXT NOT NULL,
  form TEXT,
  is_common BOOLEAN DEFAULT true
);

-- 3. Create trigram GIN indexes for fuzzy search
CREATE INDEX IF NOT EXISTS idx_medications_name_trgm ON medications USING GIN (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_medications_generic_name_trgm ON medications USING GIN (generic_name gin_trgm_ops);

-- 4. Create btree index on category
CREATE INDEX IF NOT EXISTS idx_medications_category ON medications USING btree (category);

-- 5. Enable RLS with public read policy
ALTER TABLE medications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for autocomplete"
  ON medications
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- 6. Create search RPC function
CREATE OR REPLACE FUNCTION search_medications(search_query TEXT, max_results INT DEFAULT 10)
RETURNS TABLE (
  id INT,
  name TEXT,
  generic_name TEXT,
  category TEXT,
  form TEXT
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  result_count INT;
BEGIN
  -- First try trigram similarity search
  RETURN QUERY
    SELECT m.id, m.name, m.generic_name, m.category, m.form
    FROM medications m
    WHERE similarity(m.name, search_query) > 0.1
       OR similarity(COALESCE(m.generic_name, ''), search_query) > 0.1
    ORDER BY GREATEST(
      similarity(m.name, search_query),
      similarity(COALESCE(m.generic_name, ''), search_query)
    ) DESC
    LIMIT max_results;

  GET DIAGNOSTICS result_count = ROW_COUNT;

  -- Fall back to ILIKE prefix match if trigram gives no results
  IF result_count = 0 THEN
    RETURN QUERY
      SELECT m.id, m.name, m.generic_name, m.category, m.form
      FROM medications m
      WHERE m.name ILIKE search_query || '%'
         OR m.generic_name ILIKE search_query || '%'
      ORDER BY
        CASE WHEN m.name ILIKE search_query || '%' THEN 0 ELSE 1 END,
        m.name
      LIMIT max_results;
  END IF;
END;
$$;

-- 7. Seed medications data
-- Using INSERT ... ON CONFLICT DO NOTHING for safety

-- ============================================================
-- CARDIOVASCULAR
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Atorvastatin', 'Atorvastatin', 'Cardiovascular', 'tablet'),
  ('Lipitor', 'Atorvastatin', 'Cardiovascular', 'tablet'),
  ('Simvastatin', 'Simvastatin', 'Cardiovascular', 'tablet'),
  ('Zocor', 'Simvastatin', 'Cardiovascular', 'tablet'),
  ('Rosuvastatin', 'Rosuvastatin', 'Cardiovascular', 'tablet'),
  ('Crestor', 'Rosuvastatin', 'Cardiovascular', 'tablet'),
  ('Pravastatin', 'Pravastatin', 'Cardiovascular', 'tablet'),
  ('Fluvastatin', 'Fluvastatin', 'Cardiovascular', 'capsule'),
  ('Ezetimibe', 'Ezetimibe', 'Cardiovascular', 'tablet'),
  ('Ezetrol', 'Ezetimibe', 'Cardiovascular', 'tablet'),
  ('Ramipril', 'Ramipril', 'Cardiovascular', 'capsule'),
  ('Tritace', 'Ramipril', 'Cardiovascular', 'capsule'),
  ('Lisinopril', 'Lisinopril', 'Cardiovascular', 'tablet'),
  ('Zestril', 'Lisinopril', 'Cardiovascular', 'tablet'),
  ('Enalapril', 'Enalapril', 'Cardiovascular', 'tablet'),
  ('Innovace', 'Enalapril', 'Cardiovascular', 'tablet'),
  ('Perindopril', 'Perindopril', 'Cardiovascular', 'tablet'),
  ('Coversyl', 'Perindopril', 'Cardiovascular', 'tablet'),
  ('Captopril', 'Captopril', 'Cardiovascular', 'tablet'),
  ('Losartan', 'Losartan', 'Cardiovascular', 'tablet'),
  ('Cozaar', 'Losartan', 'Cardiovascular', 'tablet'),
  ('Candesartan', 'Candesartan', 'Cardiovascular', 'tablet'),
  ('Amias', 'Candesartan', 'Cardiovascular', 'tablet'),
  ('Valsartan', 'Valsartan', 'Cardiovascular', 'capsule'),
  ('Diovan', 'Valsartan', 'Cardiovascular', 'capsule'),
  ('Irbesartan', 'Irbesartan', 'Cardiovascular', 'tablet'),
  ('Aprovel', 'Irbesartan', 'Cardiovascular', 'tablet'),
  ('Telmisartan', 'Telmisartan', 'Cardiovascular', 'tablet'),
  ('Micardis', 'Telmisartan', 'Cardiovascular', 'tablet'),
  ('Olmesartan', 'Olmesartan', 'Cardiovascular', 'tablet'),
  ('Amlodipine', 'Amlodipine', 'Cardiovascular', 'tablet'),
  ('Norvasc', 'Amlodipine', 'Cardiovascular', 'tablet'),
  ('Nifedipine', 'Nifedipine', 'Cardiovascular', 'tablet'),
  ('Adalat', 'Nifedipine', 'Cardiovascular', 'tablet'),
  ('Felodipine', 'Felodipine', 'Cardiovascular', 'tablet'),
  ('Plendil', 'Felodipine', 'Cardiovascular', 'tablet'),
  ('Diltiazem', 'Diltiazem', 'Cardiovascular', 'tablet'),
  ('Tildiem', 'Diltiazem', 'Cardiovascular', 'tablet'),
  ('Verapamil', 'Verapamil', 'Cardiovascular', 'tablet'),
  ('Bisoprolol', 'Bisoprolol', 'Cardiovascular', 'tablet'),
  ('Cardicor', 'Bisoprolol', 'Cardiovascular', 'tablet'),
  ('Atenolol', 'Atenolol', 'Cardiovascular', 'tablet'),
  ('Tenormin', 'Atenolol', 'Cardiovascular', 'tablet'),
  ('Metoprolol', 'Metoprolol', 'Cardiovascular', 'tablet'),
  ('Betaloc', 'Metoprolol', 'Cardiovascular', 'tablet'),
  ('Propranolol', 'Propranolol', 'Cardiovascular', 'tablet'),
  ('Inderal', 'Propranolol', 'Cardiovascular', 'tablet'),
  ('Nebivolol', 'Nebivolol', 'Cardiovascular', 'tablet'),
  ('Carvedilol', 'Carvedilol', 'Cardiovascular', 'tablet'),
  ('Sotalol', 'Sotalol', 'Cardiovascular', 'tablet'),
  ('Labetalol', 'Labetalol', 'Cardiovascular', 'tablet'),
  ('Bendroflumethiazide', 'Bendroflumethiazide', 'Cardiovascular', 'tablet'),
  ('Indapamide', 'Indapamide', 'Cardiovascular', 'tablet'),
  ('Furosemide', 'Furosemide', 'Cardiovascular', 'tablet'),
  ('Lasix', 'Furosemide', 'Cardiovascular', 'tablet'),
  ('Bumetanide', 'Bumetanide', 'Cardiovascular', 'tablet'),
  ('Spironolactone', 'Spironolactone', 'Cardiovascular', 'tablet'),
  ('Aldactone', 'Spironolactone', 'Cardiovascular', 'tablet'),
  ('Eplerenone', 'Eplerenone', 'Cardiovascular', 'tablet'),
  ('Doxazosin', 'Doxazosin', 'Cardiovascular', 'tablet'),
  ('Cardura', 'Doxazosin', 'Cardiovascular', 'tablet'),
  ('Hydralazine', 'Hydralazine', 'Cardiovascular', 'tablet'),
  ('Minoxidil', 'Minoxidil', 'Cardiovascular', 'tablet'),
  ('Moxonidine', 'Moxonidine', 'Cardiovascular', 'tablet'),
  ('Digoxin', 'Digoxin', 'Cardiovascular', 'tablet'),
  ('Lanoxin', 'Digoxin', 'Cardiovascular', 'tablet'),
  ('Amiodarone', 'Amiodarone', 'Cardiovascular', 'tablet'),
  ('Cordarone', 'Amiodarone', 'Cardiovascular', 'tablet'),
  ('Flecainide', 'Flecainide', 'Cardiovascular', 'tablet'),
  ('Dronedarone', 'Dronedarone', 'Cardiovascular', 'tablet'),
  ('Multaq', 'Dronedarone', 'Cardiovascular', 'tablet'),
  ('Isosorbide Mononitrate', 'Isosorbide Mononitrate', 'Cardiovascular', 'tablet'),
  ('Imdur', 'Isosorbide Mononitrate', 'Cardiovascular', 'tablet'),
  ('Glyceryl Trinitrate', 'Glyceryl Trinitrate', 'Cardiovascular', 'spray'),
  ('GTN Spray', 'Glyceryl Trinitrate', 'Cardiovascular', 'spray'),
  ('Nicorandil', 'Nicorandil', 'Cardiovascular', 'tablet'),
  ('Ivabradine', 'Ivabradine', 'Cardiovascular', 'tablet'),
  ('Procoralan', 'Ivabradine', 'Cardiovascular', 'tablet'),
  ('Sacubitril/Valsartan', 'Sacubitril/Valsartan', 'Cardiovascular', 'tablet'),
  ('Entresto', 'Sacubitril/Valsartan', 'Cardiovascular', 'tablet'),
  ('Ranolazine', 'Ranolazine', 'Cardiovascular', 'tablet'),
  ('Fenofibrate', 'Fenofibrate', 'Cardiovascular', 'capsule'),
  ('Bezafibrate', 'Bezafibrate', 'Cardiovascular', 'tablet'),
  ('Chlortalidone', 'Chlortalidone', 'Cardiovascular', 'tablet')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- NERVOUS SYSTEM / CNS
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Paracetamol', 'Paracetamol', 'Nervous System', 'tablet'),
  ('Calpol', 'Paracetamol', 'Nervous System', 'liquid'),
  ('Ibuprofen', 'Ibuprofen', 'Nervous System', 'tablet'),
  ('Nurofen', 'Ibuprofen', 'Nervous System', 'tablet'),
  ('Codeine', 'Codeine', 'Nervous System', 'tablet'),
  ('Co-codamol', 'Paracetamol/Codeine', 'Nervous System', 'tablet'),
  ('Solpadol', 'Paracetamol/Codeine', 'Nervous System', 'tablet'),
  ('Tramadol', 'Tramadol', 'Nervous System', 'capsule'),
  ('Zydol', 'Tramadol', 'Nervous System', 'capsule'),
  ('Morphine', 'Morphine', 'Nervous System', 'tablet'),
  ('MST Continus', 'Morphine', 'Nervous System', 'tablet'),
  ('Oramorph', 'Morphine', 'Nervous System', 'liquid'),
  ('Oxycodone', 'Oxycodone', 'Nervous System', 'capsule'),
  ('OxyContin', 'Oxycodone', 'Nervous System', 'tablet'),
  ('OxyNorm', 'Oxycodone', 'Nervous System', 'capsule'),
  ('Fentanyl', 'Fentanyl', 'Nervous System', 'patch'),
  ('Buprenorphine', 'Buprenorphine', 'Nervous System', 'patch'),
  ('BuTrans', 'Buprenorphine', 'Nervous System', 'patch'),
  ('Tapentadol', 'Tapentadol', 'Nervous System', 'tablet'),
  ('Palexia', 'Tapentadol', 'Nervous System', 'tablet'),
  ('Gabapentin', 'Gabapentin', 'Nervous System', 'capsule'),
  ('Neurontin', 'Gabapentin', 'Nervous System', 'capsule'),
  ('Pregabalin', 'Pregabalin', 'Nervous System', 'capsule'),
  ('Lyrica', 'Pregabalin', 'Nervous System', 'capsule'),
  ('Amitriptyline', 'Amitriptyline', 'Nervous System', 'tablet'),
  ('Nortriptyline', 'Nortriptyline', 'Nervous System', 'tablet'),
  ('Duloxetine', 'Duloxetine', 'Nervous System', 'capsule'),
  ('Cymbalta', 'Duloxetine', 'Nervous System', 'capsule'),
  ('Sumatriptan', 'Sumatriptan', 'Nervous System', 'tablet'),
  ('Imigran', 'Sumatriptan', 'Nervous System', 'tablet'),
  ('Zolmitriptan', 'Zolmitriptan', 'Nervous System', 'tablet'),
  ('Zomig', 'Zolmitriptan', 'Nervous System', 'tablet'),
  ('Rizatriptan', 'Rizatriptan', 'Nervous System', 'tablet'),
  ('Maxalt', 'Rizatriptan', 'Nervous System', 'tablet'),
  ('Pizotifen', 'Pizotifen', 'Nervous System', 'tablet'),
  ('Topiramate', 'Topiramate', 'Nervous System', 'tablet'),
  ('Topamax', 'Topiramate', 'Nervous System', 'tablet'),
  ('Carbamazepine', 'Carbamazepine', 'Nervous System', 'tablet'),
  ('Tegretol', 'Carbamazepine', 'Nervous System', 'tablet'),
  ('Sodium Valproate', 'Sodium Valproate', 'Nervous System', 'tablet'),
  ('Epilim', 'Sodium Valproate', 'Nervous System', 'tablet'),
  ('Lamotrigine', 'Lamotrigine', 'Nervous System', 'tablet'),
  ('Lamictal', 'Lamotrigine', 'Nervous System', 'tablet'),
  ('Levetiracetam', 'Levetiracetam', 'Nervous System', 'tablet'),
  ('Keppra', 'Levetiracetam', 'Nervous System', 'tablet'),
  ('Phenytoin', 'Phenytoin', 'Nervous System', 'capsule'),
  ('Epanutin', 'Phenytoin', 'Nervous System', 'capsule'),
  ('Lacosamide', 'Lacosamide', 'Nervous System', 'tablet'),
  ('Vimpat', 'Lacosamide', 'Nervous System', 'tablet'),
  ('Zonisamide', 'Zonisamide', 'Nervous System', 'capsule'),
  ('Zonegran', 'Zonisamide', 'Nervous System', 'capsule'),
  ('Clobazam', 'Clobazam', 'Nervous System', 'tablet'),
  ('Clonazepam', 'Clonazepam', 'Nervous System', 'tablet'),
  ('Co-dydramol', 'Paracetamol/Dihydrocodeine', 'Nervous System', 'tablet'),
  ('Dihydrocodeine', 'Dihydrocodeine', 'Nervous System', 'tablet'),
  ('Naproxen', 'Naproxen', 'Nervous System', 'tablet'),
  ('Naprosyn', 'Naproxen', 'Nervous System', 'tablet'),
  ('Aspirin', 'Aspirin', 'Nervous System', 'tablet')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- MENTAL HEALTH (Antidepressants, Anxiolytics, Antipsychotics)
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Sertraline', 'Sertraline', 'Mental Health', 'tablet'),
  ('Lustral', 'Sertraline', 'Mental Health', 'tablet'),
  ('Fluoxetine', 'Fluoxetine', 'Mental Health', 'capsule'),
  ('Prozac', 'Fluoxetine', 'Mental Health', 'capsule'),
  ('Citalopram', 'Citalopram', 'Mental Health', 'tablet'),
  ('Cipramil', 'Citalopram', 'Mental Health', 'tablet'),
  ('Escitalopram', 'Escitalopram', 'Mental Health', 'tablet'),
  ('Cipralex', 'Escitalopram', 'Mental Health', 'tablet'),
  ('Paroxetine', 'Paroxetine', 'Mental Health', 'tablet'),
  ('Seroxat', 'Paroxetine', 'Mental Health', 'tablet'),
  ('Venlafaxine', 'Venlafaxine', 'Mental Health', 'capsule'),
  ('Efexor', 'Venlafaxine', 'Mental Health', 'capsule'),
  ('Mirtazapine', 'Mirtazapine', 'Mental Health', 'tablet'),
  ('Zispin', 'Mirtazapine', 'Mental Health', 'tablet'),
  ('Trazodone', 'Trazodone', 'Mental Health', 'capsule'),
  ('Molipaxin', 'Trazodone', 'Mental Health', 'capsule'),
  ('Bupropion', 'Bupropion', 'Mental Health', 'tablet'),
  ('Zyban', 'Bupropion', 'Mental Health', 'tablet'),
  ('Vortioxetine', 'Vortioxetine', 'Mental Health', 'tablet'),
  ('Brintellix', 'Vortioxetine', 'Mental Health', 'tablet'),
  ('Clomipramine', 'Clomipramine', 'Mental Health', 'capsule'),
  ('Anafranil', 'Clomipramine', 'Mental Health', 'capsule'),
  ('Dosulepin', 'Dosulepin', 'Mental Health', 'capsule'),
  ('Imipramine', 'Imipramine', 'Mental Health', 'tablet'),
  ('Diazepam', 'Diazepam', 'Mental Health', 'tablet'),
  ('Valium', 'Diazepam', 'Mental Health', 'tablet'),
  ('Lorazepam', 'Lorazepam', 'Mental Health', 'tablet'),
  ('Ativan', 'Lorazepam', 'Mental Health', 'tablet'),
  ('Alprazolam', 'Alprazolam', 'Mental Health', 'tablet'),
  ('Xanax', 'Alprazolam', 'Mental Health', 'tablet'),
  ('Buspirone', 'Buspirone', 'Mental Health', 'tablet'),
  ('Hydroxyzine', 'Hydroxyzine', 'Mental Health', 'tablet'),
  ('Zopiclone', 'Zopiclone', 'Mental Health', 'tablet'),
  ('Zimovane', 'Zopiclone', 'Mental Health', 'tablet'),
  ('Zolpidem', 'Zolpidem', 'Mental Health', 'tablet'),
  ('Stilnoct', 'Zolpidem', 'Mental Health', 'tablet'),
  ('Melatonin', 'Melatonin', 'Mental Health', 'tablet'),
  ('Circadin', 'Melatonin', 'Mental Health', 'tablet'),
  ('Quetiapine', 'Quetiapine', 'Mental Health', 'tablet'),
  ('Seroquel', 'Quetiapine', 'Mental Health', 'tablet'),
  ('Olanzapine', 'Olanzapine', 'Mental Health', 'tablet'),
  ('Zyprexa', 'Olanzapine', 'Mental Health', 'tablet'),
  ('Risperidone', 'Risperidone', 'Mental Health', 'tablet'),
  ('Risperdal', 'Risperidone', 'Mental Health', 'tablet'),
  ('Aripiprazole', 'Aripiprazole', 'Mental Health', 'tablet'),
  ('Abilify', 'Aripiprazole', 'Mental Health', 'tablet'),
  ('Haloperidol', 'Haloperidol', 'Mental Health', 'tablet'),
  ('Chlorpromazine', 'Chlorpromazine', 'Mental Health', 'tablet'),
  ('Clozapine', 'Clozapine', 'Mental Health', 'tablet'),
  ('Clozaril', 'Clozapine', 'Mental Health', 'tablet'),
  ('Paliperidone', 'Paliperidone', 'Mental Health', 'tablet'),
  ('Invega', 'Paliperidone', 'Mental Health', 'tablet'),
  ('Lithium Carbonate', 'Lithium Carbonate', 'Mental Health', 'tablet'),
  ('Priadel', 'Lithium Carbonate', 'Mental Health', 'tablet'),
  ('Camcolit', 'Lithium Carbonate', 'Mental Health', 'tablet'),
  ('Promethazine', 'Promethazine', 'Mental Health', 'tablet'),
  ('Phenergan', 'Promethazine', 'Mental Health', 'tablet'),
  ('Methylphenidate', 'Methylphenidate', 'Mental Health', 'tablet'),
  ('Ritalin', 'Methylphenidate', 'Mental Health', 'tablet'),
  ('Concerta', 'Methylphenidate', 'Mental Health', 'tablet'),
  ('Lisdexamfetamine', 'Lisdexamfetamine', 'Mental Health', 'capsule'),
  ('Elvanse', 'Lisdexamfetamine', 'Mental Health', 'capsule'),
  ('Atomoxetine', 'Atomoxetine', 'Mental Health', 'capsule'),
  ('Strattera', 'Atomoxetine', 'Mental Health', 'capsule'),
  ('Guanfacine', 'Guanfacine', 'Mental Health', 'tablet'),
  ('Intuniv', 'Guanfacine', 'Mental Health', 'tablet')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- ENDOCRINE (Diabetes, Thyroid, HRT, Contraceptives)
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Metformin', 'Metformin', 'Endocrine', 'tablet'),
  ('Glucophage', 'Metformin', 'Endocrine', 'tablet'),
  ('Gliclazide', 'Gliclazide', 'Endocrine', 'tablet'),
  ('Diamicron', 'Gliclazide', 'Endocrine', 'tablet'),
  ('Glimepiride', 'Glimepiride', 'Endocrine', 'tablet'),
  ('Pioglitazone', 'Pioglitazone', 'Endocrine', 'tablet'),
  ('Actos', 'Pioglitazone', 'Endocrine', 'tablet'),
  ('Sitagliptin', 'Sitagliptin', 'Endocrine', 'tablet'),
  ('Januvia', 'Sitagliptin', 'Endocrine', 'tablet'),
  ('Linagliptin', 'Linagliptin', 'Endocrine', 'tablet'),
  ('Trajenta', 'Linagliptin', 'Endocrine', 'tablet'),
  ('Saxagliptin', 'Saxagliptin', 'Endocrine', 'tablet'),
  ('Onglyza', 'Saxagliptin', 'Endocrine', 'tablet'),
  ('Alogliptin', 'Alogliptin', 'Endocrine', 'tablet'),
  ('Vipidia', 'Alogliptin', 'Endocrine', 'tablet'),
  ('Empagliflozin', 'Empagliflozin', 'Endocrine', 'tablet'),
  ('Jardiance', 'Empagliflozin', 'Endocrine', 'tablet'),
  ('Dapagliflozin', 'Dapagliflozin', 'Endocrine', 'tablet'),
  ('Forxiga', 'Dapagliflozin', 'Endocrine', 'tablet'),
  ('Canagliflozin', 'Canagliflozin', 'Endocrine', 'tablet'),
  ('Invokana', 'Canagliflozin', 'Endocrine', 'tablet'),
  ('Semaglutide', 'Semaglutide', 'Endocrine', 'injection'),
  ('Ozempic', 'Semaglutide', 'Endocrine', 'injection'),
  ('Rybelsus', 'Semaglutide', 'Endocrine', 'tablet'),
  ('Wegovy', 'Semaglutide', 'Endocrine', 'injection'),
  ('Liraglutide', 'Liraglutide', 'Endocrine', 'injection'),
  ('Victoza', 'Liraglutide', 'Endocrine', 'injection'),
  ('Saxenda', 'Liraglutide', 'Endocrine', 'injection'),
  ('Dulaglutide', 'Dulaglutide', 'Endocrine', 'injection'),
  ('Trulicity', 'Dulaglutide', 'Endocrine', 'injection'),
  ('Exenatide', 'Exenatide', 'Endocrine', 'injection'),
  ('Byetta', 'Exenatide', 'Endocrine', 'injection'),
  ('Insulin Glargine', 'Insulin Glargine', 'Endocrine', 'injection'),
  ('Lantus', 'Insulin Glargine', 'Endocrine', 'injection'),
  ('Toujeo', 'Insulin Glargine', 'Endocrine', 'injection'),
  ('Insulin Detemir', 'Insulin Detemir', 'Endocrine', 'injection'),
  ('Levemir', 'Insulin Detemir', 'Endocrine', 'injection'),
  ('Insulin Degludec', 'Insulin Degludec', 'Endocrine', 'injection'),
  ('Tresiba', 'Insulin Degludec', 'Endocrine', 'injection'),
  ('Insulin Lispro', 'Insulin Lispro', 'Endocrine', 'injection'),
  ('Humalog', 'Insulin Lispro', 'Endocrine', 'injection'),
  ('Insulin Aspart', 'Insulin Aspart', 'Endocrine', 'injection'),
  ('NovoRapid', 'Insulin Aspart', 'Endocrine', 'injection'),
  ('Levothyroxine', 'Levothyroxine', 'Endocrine', 'tablet'),
  ('Eltroxin', 'Levothyroxine', 'Endocrine', 'tablet'),
  ('Liothyronine', 'Liothyronine', 'Endocrine', 'tablet'),
  ('Carbimazole', 'Carbimazole', 'Endocrine', 'tablet'),
  ('Propylthiouracil', 'Propylthiouracil', 'Endocrine', 'tablet'),
  ('Prednisolone', 'Prednisolone', 'Endocrine', 'tablet'),
  ('Hydrocortisone', 'Hydrocortisone', 'Endocrine', 'tablet'),
  ('Dexamethasone', 'Dexamethasone', 'Endocrine', 'tablet'),
  ('Fludrocortisone', 'Fludrocortisone', 'Endocrine', 'tablet'),
  ('Estradiol', 'Estradiol', 'Endocrine', 'patch'),
  ('Evorel', 'Estradiol', 'Endocrine', 'patch'),
  ('Oestrogel', 'Estradiol', 'Endocrine', 'gel'),
  ('Utrogestan', 'Progesterone', 'Endocrine', 'capsule'),
  ('Provera', 'Medroxyprogesterone', 'Endocrine', 'tablet'),
  ('Kliovance', 'Estradiol/Norethisterone', 'Endocrine', 'tablet'),
  ('Tibolone', 'Tibolone', 'Endocrine', 'tablet'),
  ('Livial', 'Tibolone', 'Endocrine', 'tablet'),
  ('Testosterone', 'Testosterone', 'Endocrine', 'gel'),
  ('Testogel', 'Testosterone', 'Endocrine', 'gel'),
  ('Microgynon', 'Ethinylestradiol/Levonorgestrel', 'Endocrine', 'tablet'),
  ('Rigevidon', 'Ethinylestradiol/Levonorgestrel', 'Endocrine', 'tablet'),
  ('Yasmin', 'Ethinylestradiol/Drospirenone', 'Endocrine', 'tablet'),
  ('Cilest', 'Ethinylestradiol/Norgestimate', 'Endocrine', 'tablet'),
  ('Cerelle', 'Desogestrel', 'Endocrine', 'tablet'),
  ('Cerazette', 'Desogestrel', 'Endocrine', 'tablet'),
  ('Noriday', 'Norethisterone', 'Endocrine', 'tablet'),
  ('Norethisterone', 'Norethisterone', 'Endocrine', 'tablet'),
  ('Depo-Provera', 'Medroxyprogesterone', 'Endocrine', 'injection'),
  ('Alendronic Acid', 'Alendronic Acid', 'Endocrine', 'tablet'),
  ('Fosamax', 'Alendronic Acid', 'Endocrine', 'tablet'),
  ('Risedronate', 'Risedronate', 'Endocrine', 'tablet'),
  ('Actonel', 'Risedronate', 'Endocrine', 'tablet'),
  ('Denosumab', 'Denosumab', 'Endocrine', 'injection'),
  ('Prolia', 'Denosumab', 'Endocrine', 'injection'),
  ('Orlistat', 'Orlistat', 'Endocrine', 'capsule'),
  ('Xenical', 'Orlistat', 'Endocrine', 'capsule'),
  ('Tirzepatide', 'Tirzepatide', 'Endocrine', 'injection'),
  ('Mounjaro', 'Tirzepatide', 'Endocrine', 'injection')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- RESPIRATORY
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Salbutamol', 'Salbutamol', 'Respiratory', 'inhaler'),
  ('Ventolin', 'Salbutamol', 'Respiratory', 'inhaler'),
  ('Terbutaline', 'Terbutaline', 'Respiratory', 'inhaler'),
  ('Bricanyl', 'Terbutaline', 'Respiratory', 'inhaler'),
  ('Ipratropium', 'Ipratropium', 'Respiratory', 'inhaler'),
  ('Atrovent', 'Ipratropium', 'Respiratory', 'inhaler'),
  ('Beclometasone', 'Beclometasone', 'Respiratory', 'inhaler'),
  ('Clenil', 'Beclometasone', 'Respiratory', 'inhaler'),
  ('Qvar', 'Beclometasone', 'Respiratory', 'inhaler'),
  ('Budesonide', 'Budesonide', 'Respiratory', 'inhaler'),
  ('Pulmicort', 'Budesonide', 'Respiratory', 'inhaler'),
  ('Fluticasone', 'Fluticasone', 'Respiratory', 'inhaler'),
  ('Flixotide', 'Fluticasone', 'Respiratory', 'inhaler'),
  ('Fluticasone/Salmeterol', 'Fluticasone/Salmeterol', 'Respiratory', 'inhaler'),
  ('Seretide', 'Fluticasone/Salmeterol', 'Respiratory', 'inhaler'),
  ('AirFluSal', 'Fluticasone/Salmeterol', 'Respiratory', 'inhaler'),
  ('Budesonide/Formoterol', 'Budesonide/Formoterol', 'Respiratory', 'inhaler'),
  ('Symbicort', 'Budesonide/Formoterol', 'Respiratory', 'inhaler'),
  ('DuoResp', 'Budesonide/Formoterol', 'Respiratory', 'inhaler'),
  ('Fluticasone Furoate/Vilanterol', 'Fluticasone Furoate/Vilanterol', 'Respiratory', 'inhaler'),
  ('Relvar', 'Fluticasone Furoate/Vilanterol', 'Respiratory', 'inhaler'),
  ('Salmeterol', 'Salmeterol', 'Respiratory', 'inhaler'),
  ('Serevent', 'Salmeterol', 'Respiratory', 'inhaler'),
  ('Formoterol', 'Formoterol', 'Respiratory', 'inhaler'),
  ('Oxis', 'Formoterol', 'Respiratory', 'inhaler'),
  ('Tiotropium', 'Tiotropium', 'Respiratory', 'inhaler'),
  ('Spiriva', 'Tiotropium', 'Respiratory', 'inhaler'),
  ('Glycopyrronium', 'Glycopyrronium', 'Respiratory', 'inhaler'),
  ('Seebri', 'Glycopyrronium', 'Respiratory', 'inhaler'),
  ('Umeclidinium/Vilanterol', 'Umeclidinium/Vilanterol', 'Respiratory', 'inhaler'),
  ('Anoro', 'Umeclidinium/Vilanterol', 'Respiratory', 'inhaler'),
  ('Montelukast', 'Montelukast', 'Respiratory', 'tablet'),
  ('Singulair', 'Montelukast', 'Respiratory', 'tablet'),
  ('Theophylline', 'Theophylline', 'Respiratory', 'tablet'),
  ('Uniphyllin', 'Theophylline', 'Respiratory', 'tablet'),
  ('Cetirizine', 'Cetirizine', 'Respiratory', 'tablet'),
  ('Zirtek', 'Cetirizine', 'Respiratory', 'tablet'),
  ('Loratadine', 'Loratadine', 'Respiratory', 'tablet'),
  ('Clarityn', 'Loratadine', 'Respiratory', 'tablet'),
  ('Fexofenadine', 'Fexofenadine', 'Respiratory', 'tablet'),
  ('Telfast', 'Fexofenadine', 'Respiratory', 'tablet'),
  ('Desloratadine', 'Desloratadine', 'Respiratory', 'tablet'),
  ('Neoclarityn', 'Desloratadine', 'Respiratory', 'tablet'),
  ('Levocetirizine', 'Levocetirizine', 'Respiratory', 'tablet'),
  ('Xyzal', 'Levocetirizine', 'Respiratory', 'tablet'),
  ('Chlorphenamine', 'Chlorphenamine', 'Respiratory', 'tablet'),
  ('Piriton', 'Chlorphenamine', 'Respiratory', 'tablet'),
  ('Beclometasone Nasal', 'Beclometasone', 'Respiratory', 'nasal spray'),
  ('Beconase', 'Beclometasone', 'Respiratory', 'nasal spray'),
  ('Fluticasone Nasal', 'Fluticasone', 'Respiratory', 'nasal spray'),
  ('Flixonase', 'Fluticasone', 'Respiratory', 'nasal spray'),
  ('Mometasone Nasal', 'Mometasone', 'Respiratory', 'nasal spray'),
  ('Nasonex', 'Mometasone', 'Respiratory', 'nasal spray'),
  ('Carbocisteine', 'Carbocisteine', 'Respiratory', 'capsule'),
  ('Mucodyne', 'Carbocisteine', 'Respiratory', 'capsule')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- ANTI-INFECTIVES (Antibiotics, Antivirals, Antifungals)
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Amoxicillin', 'Amoxicillin', 'Anti-infectives', 'capsule'),
  ('Amoxil', 'Amoxicillin', 'Anti-infectives', 'capsule'),
  ('Co-amoxiclav', 'Amoxicillin/Clavulanic Acid', 'Anti-infectives', 'tablet'),
  ('Augmentin', 'Amoxicillin/Clavulanic Acid', 'Anti-infectives', 'tablet'),
  ('Flucloxacillin', 'Flucloxacillin', 'Anti-infectives', 'capsule'),
  ('Floxapen', 'Flucloxacillin', 'Anti-infectives', 'capsule'),
  ('Phenoxymethylpenicillin', 'Phenoxymethylpenicillin', 'Anti-infectives', 'tablet'),
  ('Penicillin V', 'Phenoxymethylpenicillin', 'Anti-infectives', 'tablet'),
  ('Cefalexin', 'Cefalexin', 'Anti-infectives', 'capsule'),
  ('Keflex', 'Cefalexin', 'Anti-infectives', 'capsule'),
  ('Cefuroxime', 'Cefuroxime', 'Anti-infectives', 'tablet'),
  ('Zinnat', 'Cefuroxime', 'Anti-infectives', 'tablet'),
  ('Cefixime', 'Cefixime', 'Anti-infectives', 'tablet'),
  ('Clarithromycin', 'Clarithromycin', 'Anti-infectives', 'tablet'),
  ('Klaricid', 'Clarithromycin', 'Anti-infectives', 'tablet'),
  ('Azithromycin', 'Azithromycin', 'Anti-infectives', 'capsule'),
  ('Zithromax', 'Azithromycin', 'Anti-infectives', 'capsule'),
  ('Erythromycin', 'Erythromycin', 'Anti-infectives', 'tablet'),
  ('Doxycycline', 'Doxycycline', 'Anti-infectives', 'capsule'),
  ('Vibramycin', 'Doxycycline', 'Anti-infectives', 'capsule'),
  ('Lymecycline', 'Lymecycline', 'Anti-infectives', 'capsule'),
  ('Tetralysal', 'Lymecycline', 'Anti-infectives', 'capsule'),
  ('Oxytetracycline', 'Oxytetracycline', 'Anti-infectives', 'tablet'),
  ('Minocycline', 'Minocycline', 'Anti-infectives', 'capsule'),
  ('Ciprofloxacin', 'Ciprofloxacin', 'Anti-infectives', 'tablet'),
  ('Ciproxin', 'Ciprofloxacin', 'Anti-infectives', 'tablet'),
  ('Levofloxacin', 'Levofloxacin', 'Anti-infectives', 'tablet'),
  ('Moxifloxacin', 'Moxifloxacin', 'Anti-infectives', 'tablet'),
  ('Trimethoprim', 'Trimethoprim', 'Anti-infectives', 'tablet'),
  ('Nitrofurantoin', 'Nitrofurantoin', 'Anti-infectives', 'capsule'),
  ('Macrobid', 'Nitrofurantoin', 'Anti-infectives', 'capsule'),
  ('Metronidazole', 'Metronidazole', 'Anti-infectives', 'tablet'),
  ('Flagyl', 'Metronidazole', 'Anti-infectives', 'tablet'),
  ('Clindamycin', 'Clindamycin', 'Anti-infectives', 'capsule'),
  ('Dalacin', 'Clindamycin', 'Anti-infectives', 'capsule'),
  ('Co-trimoxazole', 'Sulfamethoxazole/Trimethoprim', 'Anti-infectives', 'tablet'),
  ('Septrin', 'Sulfamethoxazole/Trimethoprim', 'Anti-infectives', 'tablet'),
  ('Rifaximin', 'Rifaximin', 'Anti-infectives', 'tablet'),
  ('Aciclovir', 'Aciclovir', 'Anti-infectives', 'tablet'),
  ('Zovirax', 'Aciclovir', 'Anti-infectives', 'tablet'),
  ('Valaciclovir', 'Valaciclovir', 'Anti-infectives', 'tablet'),
  ('Valtrex', 'Valaciclovir', 'Anti-infectives', 'tablet'),
  ('Oseltamivir', 'Oseltamivir', 'Anti-infectives', 'capsule'),
  ('Tamiflu', 'Oseltamivir', 'Anti-infectives', 'capsule'),
  ('Fluconazole', 'Fluconazole', 'Anti-infectives', 'capsule'),
  ('Diflucan', 'Fluconazole', 'Anti-infectives', 'capsule'),
  ('Itraconazole', 'Itraconazole', 'Anti-infectives', 'capsule'),
  ('Sporanox', 'Itraconazole', 'Anti-infectives', 'capsule'),
  ('Terbinafine', 'Terbinafine', 'Anti-infectives', 'tablet'),
  ('Lamisil', 'Terbinafine', 'Anti-infectives', 'tablet'),
  ('Nystatin', 'Nystatin', 'Anti-infectives', 'liquid'),
  ('Griseofulvin', 'Griseofulvin', 'Anti-infectives', 'tablet')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- GASTROINTESTINAL
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Omeprazole', 'Omeprazole', 'Gastrointestinal', 'capsule'),
  ('Losec', 'Omeprazole', 'Gastrointestinal', 'capsule'),
  ('Lansoprazole', 'Lansoprazole', 'Gastrointestinal', 'capsule'),
  ('Zoton', 'Lansoprazole', 'Gastrointestinal', 'capsule'),
  ('Esomeprazole', 'Esomeprazole', 'Gastrointestinal', 'capsule'),
  ('Nexium', 'Esomeprazole', 'Gastrointestinal', 'capsule'),
  ('Pantoprazole', 'Pantoprazole', 'Gastrointestinal', 'tablet'),
  ('Protium', 'Pantoprazole', 'Gastrointestinal', 'tablet'),
  ('Rabeprazole', 'Rabeprazole', 'Gastrointestinal', 'tablet'),
  ('Pariet', 'Rabeprazole', 'Gastrointestinal', 'tablet'),
  ('Ranitidine', 'Ranitidine', 'Gastrointestinal', 'tablet'),
  ('Zantac', 'Ranitidine', 'Gastrointestinal', 'tablet'),
  ('Famotidine', 'Famotidine', 'Gastrointestinal', 'tablet'),
  ('Pepcid', 'Famotidine', 'Gastrointestinal', 'tablet'),
  ('Gaviscon', 'Sodium Alginate', 'Gastrointestinal', 'liquid'),
  ('Gaviscon Advance', 'Sodium Alginate', 'Gastrointestinal', 'liquid'),
  ('Rennie', 'Calcium Carbonate', 'Gastrointestinal', 'tablet'),
  ('Loperamide', 'Loperamide', 'Gastrointestinal', 'capsule'),
  ('Imodium', 'Loperamide', 'Gastrointestinal', 'capsule'),
  ('Mebeverine', 'Mebeverine', 'Gastrointestinal', 'tablet'),
  ('Colofac', 'Mebeverine', 'Gastrointestinal', 'tablet'),
  ('Hyoscine Butylbromide', 'Hyoscine Butylbromide', 'Gastrointestinal', 'tablet'),
  ('Buscopan', 'Hyoscine Butylbromide', 'Gastrointestinal', 'tablet'),
  ('Peppermint Oil', 'Peppermint Oil', 'Gastrointestinal', 'capsule'),
  ('Colpermin', 'Peppermint Oil', 'Gastrointestinal', 'capsule'),
  ('Mesalazine', 'Mesalazine', 'Gastrointestinal', 'tablet'),
  ('Asacol', 'Mesalazine', 'Gastrointestinal', 'tablet'),
  ('Pentasa', 'Mesalazine', 'Gastrointestinal', 'tablet'),
  ('Octasa', 'Mesalazine', 'Gastrointestinal', 'tablet'),
  ('Sulfasalazine', 'Sulfasalazine', 'Gastrointestinal', 'tablet'),
  ('Salazopyrin', 'Sulfasalazine', 'Gastrointestinal', 'tablet'),
  ('Budesonide Oral', 'Budesonide', 'Gastrointestinal', 'capsule'),
  ('Entocort', 'Budesonide', 'Gastrointestinal', 'capsule'),
  ('Lactulose', 'Lactulose', 'Gastrointestinal', 'liquid'),
  ('Macrogol', 'Macrogol', 'Gastrointestinal', 'sachet'),
  ('Movicol', 'Macrogol', 'Gastrointestinal', 'sachet'),
  ('Laxido', 'Macrogol', 'Gastrointestinal', 'sachet'),
  ('Senna', 'Senna', 'Gastrointestinal', 'tablet'),
  ('Senokot', 'Senna', 'Gastrointestinal', 'tablet'),
  ('Bisacodyl', 'Bisacodyl', 'Gastrointestinal', 'tablet'),
  ('Dulcolax', 'Bisacodyl', 'Gastrointestinal', 'tablet'),
  ('Ispaghula Husk', 'Ispaghula Husk', 'Gastrointestinal', 'sachet'),
  ('Fybogel', 'Ispaghula Husk', 'Gastrointestinal', 'sachet'),
  ('Docusate Sodium', 'Docusate Sodium', 'Gastrointestinal', 'capsule'),
  ('Prucalopride', 'Prucalopride', 'Gastrointestinal', 'tablet'),
  ('Resolor', 'Prucalopride', 'Gastrointestinal', 'tablet'),
  ('Linaclotide', 'Linaclotide', 'Gastrointestinal', 'capsule'),
  ('Constella', 'Linaclotide', 'Gastrointestinal', 'capsule'),
  ('Domperidone', 'Domperidone', 'Gastrointestinal', 'tablet'),
  ('Motilium', 'Domperidone', 'Gastrointestinal', 'tablet'),
  ('Metoclopramide', 'Metoclopramide', 'Gastrointestinal', 'tablet'),
  ('Maxolon', 'Metoclopramide', 'Gastrointestinal', 'tablet'),
  ('Ondansetron', 'Ondansetron', 'Gastrointestinal', 'tablet'),
  ('Zofran', 'Ondansetron', 'Gastrointestinal', 'tablet'),
  ('Prochlorperazine', 'Prochlorperazine', 'Gastrointestinal', 'tablet'),
  ('Stemetil', 'Prochlorperazine', 'Gastrointestinal', 'tablet'),
  ('Cyclizine', 'Cyclizine', 'Gastrointestinal', 'tablet'),
  ('Granisetron', 'Granisetron', 'Gastrointestinal', 'tablet'),
  ('Sucralfate', 'Sucralfate', 'Gastrointestinal', 'tablet'),
  ('Cholestyramine', 'Cholestyramine', 'Gastrointestinal', 'sachet'),
  ('Questran', 'Cholestyramine', 'Gastrointestinal', 'sachet'),
  ('Ursodeoxycholic Acid', 'Ursodeoxycholic Acid', 'Gastrointestinal', 'capsule'),
  ('Destolit', 'Ursodeoxycholic Acid', 'Gastrointestinal', 'tablet'),
  ('Pancreatin', 'Pancreatin', 'Gastrointestinal', 'capsule'),
  ('Creon', 'Pancreatin', 'Gastrointestinal', 'capsule')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- MUSCULOSKELETAL
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Diclofenac', 'Diclofenac', 'Musculoskeletal', 'tablet'),
  ('Voltarol', 'Diclofenac', 'Musculoskeletal', 'tablet'),
  ('Diclofenac Gel', 'Diclofenac', 'Musculoskeletal', 'gel'),
  ('Voltarol Gel', 'Diclofenac', 'Musculoskeletal', 'gel'),
  ('Meloxicam', 'Meloxicam', 'Musculoskeletal', 'tablet'),
  ('Mobic', 'Meloxicam', 'Musculoskeletal', 'tablet'),
  ('Celecoxib', 'Celecoxib', 'Musculoskeletal', 'capsule'),
  ('Celebrex', 'Celecoxib', 'Musculoskeletal', 'capsule'),
  ('Etoricoxib', 'Etoricoxib', 'Musculoskeletal', 'tablet'),
  ('Arcoxia', 'Etoricoxib', 'Musculoskeletal', 'tablet'),
  ('Indometacin', 'Indometacin', 'Musculoskeletal', 'capsule'),
  ('Piroxicam', 'Piroxicam', 'Musculoskeletal', 'capsule'),
  ('Methotrexate', 'Methotrexate', 'Musculoskeletal', 'tablet'),
  ('Metoject', 'Methotrexate', 'Musculoskeletal', 'injection'),
  ('Hydroxychloroquine', 'Hydroxychloroquine', 'Musculoskeletal', 'tablet'),
  ('Plaquenil', 'Hydroxychloroquine', 'Musculoskeletal', 'tablet'),
  ('Sulfasalazine', 'Sulfasalazine', 'Musculoskeletal', 'tablet'),
  ('Leflunomide', 'Leflunomide', 'Musculoskeletal', 'tablet'),
  ('Arava', 'Leflunomide', 'Musculoskeletal', 'tablet'),
  ('Azathioprine', 'Azathioprine', 'Musculoskeletal', 'tablet'),
  ('Imuran', 'Azathioprine', 'Musculoskeletal', 'tablet'),
  ('Mycophenolate', 'Mycophenolate Mofetil', 'Musculoskeletal', 'capsule'),
  ('CellCept', 'Mycophenolate Mofetil', 'Musculoskeletal', 'capsule'),
  ('Adalimumab', 'Adalimumab', 'Musculoskeletal', 'injection'),
  ('Humira', 'Adalimumab', 'Musculoskeletal', 'injection'),
  ('Etanercept', 'Etanercept', 'Musculoskeletal', 'injection'),
  ('Enbrel', 'Etanercept', 'Musculoskeletal', 'injection'),
  ('Allopurinol', 'Allopurinol', 'Musculoskeletal', 'tablet'),
  ('Zyloric', 'Allopurinol', 'Musculoskeletal', 'tablet'),
  ('Febuxostat', 'Febuxostat', 'Musculoskeletal', 'tablet'),
  ('Adenuric', 'Febuxostat', 'Musculoskeletal', 'tablet'),
  ('Colchicine', 'Colchicine', 'Musculoskeletal', 'tablet'),
  ('Baclofen', 'Baclofen', 'Musculoskeletal', 'tablet'),
  ('Lioresal', 'Baclofen', 'Musculoskeletal', 'tablet'),
  ('Tizanidine', 'Tizanidine', 'Musculoskeletal', 'tablet'),
  ('Zanaflex', 'Tizanidine', 'Musculoskeletal', 'tablet'),
  ('Methocarbamol', 'Methocarbamol', 'Musculoskeletal', 'tablet'),
  ('Robaxin', 'Methocarbamol', 'Musculoskeletal', 'tablet'),
  ('Capsaicin Cream', 'Capsaicin', 'Musculoskeletal', 'cream'),
  ('Glucosamine', 'Glucosamine', 'Musculoskeletal', 'tablet')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- BLOOD (Anticoagulants, Antiplatelets, Iron)
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Warfarin', 'Warfarin', 'Blood', 'tablet'),
  ('Rivaroxaban', 'Rivaroxaban', 'Blood', 'tablet'),
  ('Xarelto', 'Rivaroxaban', 'Blood', 'tablet'),
  ('Apixaban', 'Apixaban', 'Blood', 'tablet'),
  ('Eliquis', 'Apixaban', 'Blood', 'tablet'),
  ('Edoxaban', 'Edoxaban', 'Blood', 'tablet'),
  ('Lixiana', 'Edoxaban', 'Blood', 'tablet'),
  ('Dabigatran', 'Dabigatran', 'Blood', 'capsule'),
  ('Pradaxa', 'Dabigatran', 'Blood', 'capsule'),
  ('Enoxaparin', 'Enoxaparin', 'Blood', 'injection'),
  ('Clexane', 'Enoxaparin', 'Blood', 'injection'),
  ('Dalteparin', 'Dalteparin', 'Blood', 'injection'),
  ('Fragmin', 'Dalteparin', 'Blood', 'injection'),
  ('Tinzaparin', 'Tinzaparin', 'Blood', 'injection'),
  ('Innohep', 'Tinzaparin', 'Blood', 'injection'),
  ('Heparin', 'Heparin', 'Blood', 'injection'),
  ('Clopidogrel', 'Clopidogrel', 'Blood', 'tablet'),
  ('Plavix', 'Clopidogrel', 'Blood', 'tablet'),
  ('Ticagrelor', 'Ticagrelor', 'Blood', 'tablet'),
  ('Brilique', 'Ticagrelor', 'Blood', 'tablet'),
  ('Prasugrel', 'Prasugrel', 'Blood', 'tablet'),
  ('Efient', 'Prasugrel', 'Blood', 'tablet'),
  ('Dipyridamole', 'Dipyridamole', 'Blood', 'capsule'),
  ('Persantin', 'Dipyridamole', 'Blood', 'capsule'),
  ('Aspirin 75mg', 'Aspirin', 'Blood', 'tablet'),
  ('Ferrous Fumarate', 'Ferrous Fumarate', 'Blood', 'tablet'),
  ('Galfer', 'Ferrous Fumarate', 'Blood', 'capsule'),
  ('Ferrous Sulphate', 'Ferrous Sulphate', 'Blood', 'tablet'),
  ('Ferrous Gluconate', 'Ferrous Gluconate', 'Blood', 'tablet'),
  ('Ferinject', 'Ferric Carboxymaltose', 'Blood', 'injection'),
  ('Folic Acid', 'Folic Acid', 'Blood', 'tablet'),
  ('Hydroxocobalamin', 'Hydroxocobalamin', 'Blood', 'injection'),
  ('Cyanocobalamin', 'Cyanocobalamin', 'Blood', 'tablet'),
  ('Tranexamic Acid', 'Tranexamic Acid', 'Blood', 'tablet'),
  ('Cyklokapron', 'Tranexamic Acid', 'Blood', 'tablet'),
  ('Darbepoetin', 'Darbepoetin Alfa', 'Blood', 'injection'),
  ('Aranesp', 'Darbepoetin Alfa', 'Blood', 'injection'),
  ('Epoetin', 'Epoetin Alfa', 'Blood', 'injection')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- DERMATOLOGICAL
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Hydrocortisone Cream', 'Hydrocortisone', 'Dermatological', 'cream'),
  ('Betamethasone Cream', 'Betamethasone', 'Dermatological', 'cream'),
  ('Betnovate', 'Betamethasone', 'Dermatological', 'cream'),
  ('Clobetasol', 'Clobetasol', 'Dermatological', 'cream'),
  ('Dermovate', 'Clobetasol', 'Dermatological', 'cream'),
  ('Mometasone Cream', 'Mometasone', 'Dermatological', 'cream'),
  ('Elocon', 'Mometasone', 'Dermatological', 'cream'),
  ('Fluocinolone', 'Fluocinolone', 'Dermatological', 'cream'),
  ('Synalar', 'Fluocinolone', 'Dermatological', 'cream'),
  ('Clobetasone', 'Clobetasone', 'Dermatological', 'cream'),
  ('Eumovate', 'Clobetasone', 'Dermatological', 'cream'),
  ('Fluticasone Cream', 'Fluticasone', 'Dermatological', 'cream'),
  ('Cutivate', 'Fluticasone', 'Dermatological', 'cream'),
  ('Diprobase', 'Emollient', 'Dermatological', 'cream'),
  ('Cetraben', 'Emollient', 'Dermatological', 'cream'),
  ('Doublebase', 'Emollient', 'Dermatological', 'gel'),
  ('E45', 'Emollient', 'Dermatological', 'cream'),
  ('Aveeno', 'Emollient', 'Dermatological', 'cream'),
  ('Epaderm', 'Emollient', 'Dermatological', 'ointment'),
  ('Aqueous Cream', 'Emollient', 'Dermatological', 'cream'),
  ('Zerobase', 'Emollient', 'Dermatological', 'cream'),
  ('Dermol', 'Emollient', 'Dermatological', 'cream'),
  ('Tacrolimus Ointment', 'Tacrolimus', 'Dermatological', 'ointment'),
  ('Protopic', 'Tacrolimus', 'Dermatological', 'ointment'),
  ('Pimecrolimus', 'Pimecrolimus', 'Dermatological', 'cream'),
  ('Elidel', 'Pimecrolimus', 'Dermatological', 'cream'),
  ('Fusidic Acid Cream', 'Fusidic Acid', 'Dermatological', 'cream'),
  ('Fucidin Cream', 'Fusidic Acid', 'Dermatological', 'cream'),
  ('Mupirocin', 'Mupirocin', 'Dermatological', 'ointment'),
  ('Bactroban', 'Mupirocin', 'Dermatological', 'ointment'),
  ('Clotrimazole Cream', 'Clotrimazole', 'Dermatological', 'cream'),
  ('Canesten', 'Clotrimazole', 'Dermatological', 'cream'),
  ('Miconazole Cream', 'Miconazole', 'Dermatological', 'cream'),
  ('Daktarin', 'Miconazole', 'Dermatological', 'cream'),
  ('Ketoconazole Shampoo', 'Ketoconazole', 'Dermatological', 'shampoo'),
  ('Nizoral', 'Ketoconazole', 'Dermatological', 'shampoo'),
  ('Terbinafine Cream', 'Terbinafine', 'Dermatological', 'cream'),
  ('Lamisil Cream', 'Terbinafine', 'Dermatological', 'cream'),
  ('Aciclovir Cream', 'Aciclovir', 'Dermatological', 'cream'),
  ('Zovirax Cream', 'Aciclovir', 'Dermatological', 'cream'),
  ('Permethrin', 'Permethrin', 'Dermatological', 'cream'),
  ('Lyclear', 'Permethrin', 'Dermatological', 'cream'),
  ('Calcipotriol', 'Calcipotriol', 'Dermatological', 'ointment'),
  ('Dovonex', 'Calcipotriol', 'Dermatological', 'ointment'),
  ('Calcipotriol/Betamethasone', 'Calcipotriol/Betamethasone', 'Dermatological', 'ointment'),
  ('Enstilar', 'Calcipotriol/Betamethasone', 'Dermatological', 'foam'),
  ('Dovobet', 'Calcipotriol/Betamethasone', 'Dermatological', 'ointment'),
  ('Adapalene', 'Adapalene', 'Dermatological', 'gel'),
  ('Differin', 'Adapalene', 'Dermatological', 'gel'),
  ('Tretinoin', 'Tretinoin', 'Dermatological', 'cream'),
  ('Benzoyl Peroxide', 'Benzoyl Peroxide', 'Dermatological', 'gel'),
  ('Isotretinoin', 'Isotretinoin', 'Dermatological', 'capsule'),
  ('Roaccutane', 'Isotretinoin', 'Dermatological', 'capsule'),
  ('Azelaic Acid', 'Azelaic Acid', 'Dermatological', 'cream'),
  ('Skinoren', 'Azelaic Acid', 'Dermatological', 'cream'),
  ('Coal Tar', 'Coal Tar', 'Dermatological', 'shampoo'),
  ('Silver Sulfadiazine', 'Silver Sulfadiazine', 'Dermatological', 'cream'),
  ('Flamazine', 'Silver Sulfadiazine', 'Dermatological', 'cream')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- OPHTHALMOLOGY
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Chloramphenicol Eye Drops', 'Chloramphenicol', 'Ophthalmology', 'eye drops'),
  ('Fusidic Acid Eye Drops', 'Fusidic Acid', 'Ophthalmology', 'eye drops'),
  ('Fucithalmic', 'Fusidic Acid', 'Ophthalmology', 'eye drops'),
  ('Timolol Eye Drops', 'Timolol', 'Ophthalmology', 'eye drops'),
  ('Latanoprost Eye Drops', 'Latanoprost', 'Ophthalmology', 'eye drops'),
  ('Xalatan', 'Latanoprost', 'Ophthalmology', 'eye drops'),
  ('Bimatoprost Eye Drops', 'Bimatoprost', 'Ophthalmology', 'eye drops'),
  ('Lumigan', 'Bimatoprost', 'Ophthalmology', 'eye drops'),
  ('Travoprost Eye Drops', 'Travoprost', 'Ophthalmology', 'eye drops'),
  ('Travatan', 'Travoprost', 'Ophthalmology', 'eye drops'),
  ('Dorzolamide Eye Drops', 'Dorzolamide', 'Ophthalmology', 'eye drops'),
  ('Trusopt', 'Dorzolamide', 'Ophthalmology', 'eye drops'),
  ('Brimonidine Eye Drops', 'Brimonidine', 'Ophthalmology', 'eye drops'),
  ('Alphagan', 'Brimonidine', 'Ophthalmology', 'eye drops'),
  ('Dexamethasone Eye Drops', 'Dexamethasone', 'Ophthalmology', 'eye drops'),
  ('Maxidex', 'Dexamethasone', 'Ophthalmology', 'eye drops'),
  ('Prednisolone Eye Drops', 'Prednisolone', 'Ophthalmology', 'eye drops'),
  ('Pred Forte', 'Prednisolone', 'Ophthalmology', 'eye drops'),
  ('Hypromellose Eye Drops', 'Hypromellose', 'Ophthalmology', 'eye drops'),
  ('Carbomer Eye Gel', 'Carbomer', 'Ophthalmology', 'eye gel'),
  ('Viscotears', 'Carbomer', 'Ophthalmology', 'eye gel'),
  ('Hylo-Tear', 'Sodium Hyaluronate', 'Ophthalmology', 'eye drops'),
  ('Sodium Cromoglicate Eye Drops', 'Sodium Cromoglicate', 'Ophthalmology', 'eye drops'),
  ('Opticrom', 'Sodium Cromoglicate', 'Ophthalmology', 'eye drops'),
  ('Olopatadine Eye Drops', 'Olopatadine', 'Ophthalmology', 'eye drops'),
  ('Opatanol', 'Olopatadine', 'Ophthalmology', 'eye drops'),
  ('Ciclosporin Eye Drops', 'Ciclosporin', 'Ophthalmology', 'eye drops'),
  ('Ikervis', 'Ciclosporin', 'Ophthalmology', 'eye drops')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- VITAMINS & SUPPLEMENTS
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Vitamin D3', 'Colecalciferol', 'Vitamins & Supplements', 'capsule'),
  ('Colecalciferol', 'Colecalciferol', 'Vitamins & Supplements', 'capsule'),
  ('Fultium-D3', 'Colecalciferol', 'Vitamins & Supplements', 'capsule'),
  ('InVita D3', 'Colecalciferol', 'Vitamins & Supplements', 'liquid'),
  ('Adcal-D3', 'Calcium/Colecalciferol', 'Vitamins & Supplements', 'tablet'),
  ('Calcichew-D3', 'Calcium/Colecalciferol', 'Vitamins & Supplements', 'tablet'),
  ('Calcium Carbonate', 'Calcium Carbonate', 'Vitamins & Supplements', 'tablet'),
  ('Vitamin B12', 'Cyanocobalamin', 'Vitamins & Supplements', 'tablet'),
  ('Vitamin B Complex', 'Vitamin B Complex', 'Vitamins & Supplements', 'tablet'),
  ('Thiamine', 'Thiamine', 'Vitamins & Supplements', 'tablet'),
  ('Pabrinex', 'Vitamins B and C', 'Vitamins & Supplements', 'injection'),
  ('Vitamin C', 'Ascorbic Acid', 'Vitamins & Supplements', 'tablet'),
  ('Vitamin K', 'Phytomenadione', 'Vitamins & Supplements', 'tablet'),
  ('Potassium Chloride', 'Potassium Chloride', 'Vitamins & Supplements', 'tablet'),
  ('Sando-K', 'Potassium Chloride', 'Vitamins & Supplements', 'tablet'),
  ('Magnesium Glycinate', 'Magnesium', 'Vitamins & Supplements', 'tablet'),
  ('Zinc', 'Zinc', 'Vitamins & Supplements', 'tablet'),
  ('Omega-3', 'Omega-3 Fatty Acids', 'Vitamins & Supplements', 'capsule'),
  ('Alfacalcidol', 'Alfacalcidol', 'Vitamins & Supplements', 'capsule'),
  ('One-Alpha', 'Alfacalcidol', 'Vitamins & Supplements', 'capsule')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- UROLOGY
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Tamsulosin', 'Tamsulosin', 'Urology', 'capsule'),
  ('Flomax', 'Tamsulosin', 'Urology', 'capsule'),
  ('Alfuzosin', 'Alfuzosin', 'Urology', 'tablet'),
  ('Xatral', 'Alfuzosin', 'Urology', 'tablet'),
  ('Finasteride', 'Finasteride', 'Urology', 'tablet'),
  ('Proscar', 'Finasteride', 'Urology', 'tablet'),
  ('Dutasteride', 'Dutasteride', 'Urology', 'capsule'),
  ('Avodart', 'Dutasteride', 'Urology', 'capsule'),
  ('Solifenacin', 'Solifenacin', 'Urology', 'tablet'),
  ('Vesicare', 'Solifenacin', 'Urology', 'tablet'),
  ('Tolterodine', 'Tolterodine', 'Urology', 'capsule'),
  ('Detrusitol', 'Tolterodine', 'Urology', 'capsule'),
  ('Oxybutynin', 'Oxybutynin', 'Urology', 'tablet'),
  ('Ditropan', 'Oxybutynin', 'Urology', 'tablet'),
  ('Mirabegron', 'Mirabegron', 'Urology', 'tablet'),
  ('Betmiga', 'Mirabegron', 'Urology', 'tablet'),
  ('Fesoterodine', 'Fesoterodine', 'Urology', 'tablet'),
  ('Toviaz', 'Fesoterodine', 'Urology', 'tablet'),
  ('Darifenacin', 'Darifenacin', 'Urology', 'tablet'),
  ('Emselex', 'Darifenacin', 'Urology', 'tablet'),
  ('Desmopressin', 'Desmopressin', 'Urology', 'tablet'),
  ('DDAVP', 'Desmopressin', 'Urology', 'tablet'),
  ('Sildenafil', 'Sildenafil', 'Urology', 'tablet'),
  ('Viagra', 'Sildenafil', 'Urology', 'tablet'),
  ('Tadalafil', 'Tadalafil', 'Urology', 'tablet'),
  ('Cialis', 'Tadalafil', 'Urology', 'tablet'),
  ('Vardenafil', 'Vardenafil', 'Urology', 'tablet'),
  ('Levitra', 'Vardenafil', 'Urology', 'tablet'),
  ('Potassium Citrate', 'Potassium Citrate', 'Urology', 'liquid'),
  ('Trospium', 'Trospium', 'Urology', 'tablet'),
  ('Regurin', 'Trospium', 'Urology', 'tablet')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- IMMUNOLOGY
-- ============================================================
INSERT INTO medications (name, generic_name, category, form) VALUES
  ('Ciclosporin', 'Ciclosporin', 'Immunology', 'capsule'),
  ('Neoral', 'Ciclosporin', 'Immunology', 'capsule'),
  ('Tacrolimus', 'Tacrolimus', 'Immunology', 'capsule'),
  ('Prograf', 'Tacrolimus', 'Immunology', 'capsule'),
  ('Advagraf', 'Tacrolimus', 'Immunology', 'capsule'),
  ('Sirolimus', 'Sirolimus', 'Immunology', 'tablet'),
  ('Rapamune', 'Sirolimus', 'Immunology', 'tablet'),
  ('Infliximab', 'Infliximab', 'Immunology', 'injection'),
  ('Remicade', 'Infliximab', 'Immunology', 'injection'),
  ('Rituximab', 'Rituximab', 'Immunology', 'injection'),
  ('MabThera', 'Rituximab', 'Immunology', 'injection'),
  ('Secukinumab', 'Secukinumab', 'Immunology', 'injection'),
  ('Cosentyx', 'Secukinumab', 'Immunology', 'injection'),
  ('Ustekinumab', 'Ustekinumab', 'Immunology', 'injection'),
  ('Stelara', 'Ustekinumab', 'Immunology', 'injection'),
  ('Dupilumab', 'Dupilumab', 'Immunology', 'injection'),
  ('Dupixent', 'Dupilumab', 'Immunology', 'injection'),
  ('Omalizumab', 'Omalizumab', 'Immunology', 'injection'),
  ('Xolair', 'Omalizumab', 'Immunology', 'injection'),
  ('Tofacitinib', 'Tofacitinib', 'Immunology', 'tablet'),
  ('Xeljanz', 'Tofacitinib', 'Immunology', 'tablet'),
  ('Baricitinib', 'Baricitinib', 'Immunology', 'tablet'),
  ('Olumiant', 'Baricitinib', 'Immunology', 'tablet'),
  ('Upadacitinib', 'Upadacitinib', 'Immunology', 'tablet'),
  ('Rinvoq', 'Upadacitinib', 'Immunology', 'tablet'),
  ('Certolizumab', 'Certolizumab Pegol', 'Immunology', 'injection'),
  ('Cimzia', 'Certolizumab Pegol', 'Immunology', 'injection'),
  ('Golimumab', 'Golimumab', 'Immunology', 'injection'),
  ('Simponi', 'Golimumab', 'Immunology', 'injection'),
  ('Vedolizumab', 'Vedolizumab', 'Immunology', 'injection'),
  ('Entyvio', 'Vedolizumab', 'Immunology', 'injection'),
  ('Abatacept', 'Abatacept', 'Immunology', 'injection'),
  ('Orencia', 'Abatacept', 'Immunology', 'injection'),
  ('Tocilizumab', 'Tocilizumab', 'Immunology', 'injection'),
  ('RoActemra', 'Tocilizumab', 'Immunology', 'injection'),
  ('Ixekizumab', 'Ixekizumab', 'Immunology', 'injection'),
  ('Taltz', 'Ixekizumab', 'Immunology', 'injection'),
  ('Guselkumab', 'Guselkumab', 'Immunology', 'injection'),
  ('Tremfya', 'Guselkumab', 'Immunology', 'injection'),
  ('Epinephrine Auto-Injector', 'Epinephrine', 'Immunology', 'injection'),
  ('EpiPen', 'Epinephrine', 'Immunology', 'injection'),
  ('Jext', 'Epinephrine', 'Immunology', 'injection')
ON CONFLICT (name) DO NOTHING;
