import { Card, CardContent } from "@/components/ui/card";

/**
 * Default (cross-region) Terms of Service.
 *
 * This is the content served on .com, .eu, and any non-UK host. The UK
 * variant (`terms-uk.tsx`) is served on .co.uk with additional CQC-aware
 * positioning and regulatory disclosures.
 *
 * IMPORTANT: Do not edit this file to make UK-specific changes. Those belong
 * in `terms-uk.tsx`. This content should stay byte-for-byte equivalent to
 * what we've always served on .com/.eu unless a global update is needed.
 */

const EFFECTIVE_DATE = "17 March 2026";
const COMPANY = "MyDoctors360";

export function TermsDefault() {
  return (
    <div className="mx-auto max-w-4xl space-y-8 py-12">
      <div>
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-muted-foreground">
          Effective Date: {EFFECTIVE_DATE}
        </p>
      </div>

      <Card>
        <CardContent className="prose prose-sm max-w-none p-6 dark:prose-invert sm:p-8">
          <h2>1. Introduction</h2>
          <p>
            Welcome to {COMPANY}. These Terms of Service (&ldquo;Terms&rdquo;) govern your use of our healthcare
            marketplace platform. By creating an account or using our services, you agree to be bound by these Terms.
          </p>

          <h2>2. Platform Description</h2>
          <p>
            {COMPANY} is a marketplace that connects patients with private healthcare practitioners.
            We facilitate the discovery, booking, and payment of medical consultations. We are <strong>not</strong> a
            healthcare provider and do not provide medical advice.
          </p>

          <h2>3. Eligibility</h2>
          <ul>
            <li>You must be at least 16 years old to create an account.</li>
            <li>Doctors must hold a valid GMC registration (or equivalent) to list on our platform.</li>
            <li>You must provide accurate and complete information during registration.</li>
          </ul>

          <h2>4. User Accounts</h2>
          <ul>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You must not share your account or allow others to access it.</li>
            <li>We recommend enabling multi-factor authentication for enhanced security.</li>
            <li>We reserve the right to suspend or terminate accounts that violate these Terms.</li>
          </ul>

          <h2>5. Bookings &amp; Payments</h2>
          <h3>5.1 Booking Process</h3>
          <p>
            Bookings are confirmed only upon successful payment. Unpaid bookings expire automatically
            (15 minutes for patient-initiated, 48 hours for admin-created bookings).
          </p>

          <h3>5.2 Payments</h3>
          <p>
            All payments are processed securely via Stripe.
            Prices are displayed in the doctor&apos;s base currency. We do not store credit card details.
          </p>

          <h3>5.3 Cancellation &amp; Refunds</h3>
          <p>
            Each doctor sets their own cancellation policy (flexible, moderate, or strict).
            Refund eligibility depends on the policy and the time remaining before the appointment:
          </p>
          <ul>
            <li><strong>Flexible</strong> — Full refund if cancelled more than 24 hours before.</li>
            <li><strong>Moderate</strong> — Full refund if 48+ hours; 50% if 24-48 hours; no refund under 24 hours.</li>
            <li><strong>Strict</strong> — Full refund only if cancelled more than 72 hours before.</li>
          </ul>

          <h2>6. Doctor Responsibilities</h2>
          <ul>
            <li>Maintain valid professional registration and insurance.</li>
            <li>Provide accurate availability and pricing information.</li>
            <li>Deliver consultations in accordance with professional medical standards.</li>
            <li>Maintain patient confidentiality in compliance with GMC guidelines.</li>
          </ul>

          <h2>7. Patient Responsibilities</h2>
          <ul>
            <li>Provide accurate medical information when requested.</li>
            <li>Attend booked appointments or cancel in accordance with the cancellation policy.</li>
            <li>Follow up with your NHS GP or emergency services for urgent medical needs.</li>
          </ul>

          <h2>8. Medical Disclaimer</h2>
          <p>
            {COMPANY} is a marketplace platform, not a medical practice. We do not:
          </p>
          <ul>
            <li>Provide medical advice, diagnoses, or treatment.</li>
            <li>Guarantee the qualifications or quality of listed practitioners (though we verify GMC registration).</li>
            <li>Bear responsibility for the medical outcomes of consultations.</li>
          </ul>
          <p>
            In a medical emergency, call <strong>999</strong> or attend A&amp;E immediately. Do not rely on this
            platform for urgent medical care.
          </p>

          <h2>9. Intellectual Property</h2>
          <p>
            All content, design, and functionality of the platform are owned by {COMPANY}. Users retain
            ownership of content they submit (reviews, medical information) but grant us a licence to
            display it as necessary for platform operation.
          </p>

          <h2>10. Prohibited Conduct</h2>
          <ul>
            <li>Impersonating another person or healthcare professional.</li>
            <li>Using the platform for illegal purposes.</li>
            <li>Attempting to circumvent security measures.</li>
            <li>Posting false reviews or misleading information.</li>
            <li>Harassing other users or staff.</li>
          </ul>

          <h2>11. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, {COMPANY} is not liable for:
          </p>
          <ul>
            <li>Medical outcomes from consultations booked through our platform.</li>
            <li>Loss of data beyond our reasonable control.</li>
            <li>Service interruptions due to third-party providers.</li>
            <li>Indirect, incidental, or consequential damages.</li>
          </ul>

          <h2>12. Privacy</h2>
          <p>
            Your use of {COMPANY} is also governed by our <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>,
            which describes how we collect, use, and protect your personal data.
          </p>

          <h2>13. Governing Law</h2>
          <p>
            These Terms are governed by the laws of England and Wales. Disputes will be subject to the
            exclusive jurisdiction of the English courts.
          </p>

          <h2>14. Changes to Terms</h2>
          <p>
            We may update these Terms periodically. Material changes will be notified via email.
            Continued use of the platform after notification constitutes acceptance of the updated Terms.
          </p>

          <h2>15. Contact</h2>
          <p>
            For questions about these Terms: <strong>legal@mydoctors360.com</strong>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
